const API_BASE_URL = '/api'; // Base URL for all API endpoints, adjust as needed

const ApiRoutes = {
  AUTH: {
    LOGIN: `${API_BASE_URL}/auth/staff/login/`,
  },
  TRANSFERS: {
    ADD_TRANSFER: `${API_BASE_URL}/transfer/`,
    TRANSFER_LOCATION: `${API_BASE_URL}/location/`,
    TRANSFER_TARIFF: `${API_BASE_URL}/TransferTariff/`,
    VEHICLE_TYPE_TRANSFER_TARIFF: `${API_BASE_URL}/TransferTariff/deletevehicletypetransfertariff`,
    VEHICLE_TYPE_TRANSFER_TARIFF_STATUS: `${API_BASE_URL}/TransferTariff/statusUpdate/`,
    TRANSFER_TARIFF_CANCELLATION_POLICY: `${API_BASE_URL}/TransferTariffCancellationPolicy/`,
    TRANSFER_TARIFF_STOP_SALE: `${API_BASE_URL}/StopSale/`,
  },
  HOTELS: {
    INVENTORY_ROOM_CATEGORY: `${API_BASE_URL}/inventoryRoom/`,
    HOTEL_AMENITY: `${API_BASE_URL}/hotelAmenity/`,
    HOTEL_LOCATION: `${API_BASE_URL}/hotelLocation/`,
    ROOM_MEAL: `${API_BASE_URL}/roomMeal/`,
    ROOM_VIEW: `${API_BASE_URL}/roomView/`,
    SUPPLEMENTS: `${API_BASE_URL}/supplement/`,
    MASTERS_HOTELS: `${API_BASE_URL}/hotel/`,
    ROOM_CATEGORY: `${API_BASE_URL}/roomCategory/`,
    PREFERRED_HOTEL: `${API_BASE_URL}/preferredhotel/`,
    SPECIAL_REQUESTS: `${API_BASE_URL}/specialRequest/`,
    IMPORTS: {
      BASE: `${API_BASE_URL}/imports`,
      FROM_URL: `${API_BASE_URL}/imports/from-url`,
      STATUS: (id) => `${API_BASE_URL}/imports/${id}`,
      ERRORS: (id) => `${API_BASE_URL}/imports/${id}/errors`,
      DOWNLOAD_ERRORS: (id) => `${API_BASE_URL}/imports/${id}/download-errors`,
      DEBUG: (id) => `${API_BASE_URL}/imports/${id}/debug`,
      REGENERATE: (id) => `${API_BASE_URL}/imports/${id}/regenerate-report`,
      CLEANUP: `${API_BASE_URL}/imports/cleanup`,
    },
  },
  TOURS_AND_ACTIVITIES: {
    TOURS: `${API_BASE_URL}/tour/`,
    ACTIVITY_TYPE: `${API_BASE_URL}/activityType/`,
    ACTIVITY_SUB_TYPE: `${API_BASE_URL}/subActivityType/`,
    ACTIVITY_CATEGORY: `${API_BASE_URL}/activityCategory/`,
  },
  SUPPLIERS: {
    OFFLINE: {
      SUPPLIER: `${API_BASE_URL}/offlineSupplier/`,
      STATUS: `${API_BASE_URL}/offlineSupplier/statusUpdate/`,
      VCC_SETTING: `${API_BASE_URL}/offlineSupplier/VccSetting/`,
      TAX_REGISTRATION: `${API_BASE_URL}/offlineSupplier/TaxRegistration/`,
      DOCUMENTS: `${API_BASE_URL}/offlineSupplier/UploadDocuments/`,
      TOUR_MAPPING: `${API_BASE_URL}/offlineSupplier/mapTour/`,
      TRANSFER_MAPPING: `${API_BASE_URL}/offlineSupplier/mapTransfer/`,
      MARKUPS: `${API_BASE_URL}/offlineSupplier/updateMarkups/`,
      LOCAL_EXCLUDE_OR_INCLUDE: `${API_BASE_URL}/offlineSupplier/updateLocalExcludeInclude/`,
      MARKUP_INCLUDE_EXCLUDE: `${API_BASE_URL}/offlineSupplier/updateSupplierMarkupIncludeExclude/`,
    },
    ONLINE: {
      SUPPLIER: `${API_BASE_URL}/onlineSupplier/`,
      SEARCH_REPORT_CONFIG: `${API_BASE_URL}/onlineSupplier/OnlineSupplierReportConfig/`,
      SEARCH_REPORT_CONFIG_STATUS: `${API_BASE_URL}/onlineSupplier/OnlineSupplierReportConfig/statusUpdate/`,
      STATUS: `${API_BASE_URL}/onlineSupplier/statusUpdate/`,
      MARKUP_UPDATE: `${API_BASE_URL}/onlineSupplier/OnlineSupplierMarkupUpdate`,
      LEAD_TIME_HOURS: `${API_BASE_URL}/onlineSupplier/updateLeadTimeHrs/`,
      EXCLUDE_OR_INCLUDE: `${API_BASE_URL}/onlineSupplier/updateExcludeorInclude/`,
      API: `${API_BASE_URL}/suppliers/`,
    },
  },
  VEHICLES: {
    VEHICLE: `${API_BASE_URL}/vehicle/`,
  },
  CURRENCIES: {
    CURRENCY: `${API_BASE_URL}/currency/`,
  },
  LOYALTY_PROGRAM: {
    TIERS: `${API_BASE_URL}/loyaltyTier/`,
    REWARDS: `${API_BASE_URL}/loyaltyProduct/`,
    PRODUCT_CATEGORY: `${API_BASE_URL}/loyaltyProductCategory/`,
  },
  PAYMENT_GATEWAYS: {
    GATEWAY: `${API_BASE_URL}/paymentGateway/`,
    LIMIT_PER_TRANSACTION: `${API_BASE_URL}/paymentGateway/Transactionlimit`,
  },
  MARKUP_PROFILE: {
    PROFILE: `${API_BASE_URL}/markupProfile/`,
    ASSIGN_PROFILE: `${API_BASE_URL}/markupProfile/AssignMarkup/`,
    PROFILE_DETAIL: `${API_BASE_URL}/markupProfile/profileDetail/`,
  },
  CUSTOMER_AGENTS: {
    AGENT: `${API_BASE_URL}/agent/`,
    AGENT_EMAILS: `${API_BASE_URL}/agent/agentEmails/`,
    AGENT_DOCUMENTS: `${API_BASE_URL}/agent/UploadDocuments/`,
    AGENT_PAYMENT_GATEWAYS: `${API_BASE_URL}/agent/assignpaymentGateway/`,
    SUB_AGENT: `${API_BASE_URL}/agent/SubAgent/`,
    UPDATE_SUB_AGENT: `${API_BASE_URL}/agent/UpdateSubAgent/`,
    SUB_AGENT_EMAILS: `${API_BASE_URL}/agent/subagentEmails/`,
    DELETE_SUB_AGENT: `${API_BASE_URL}/agent/deleteSubAgent/`,
  },
  PACKAGES: {
    THEME: `${API_BASE_URL}/themeCategory/`,
    NEW_LEVELS: `${API_BASE_URL}/physicalLevel/`,
    COUNTRY_CITY_INFO: `${API_BASE_URL}/cityInformation/`,
    ESSENTIAL_INFORMATION: `${API_BASE_URL}/peakageEssentialInformation/`,
    USEFUL_INFORMATION: `${API_BASE_URL}/detailInformation/`,
    GALLERY_IMAGE: `${API_BASE_URL}/detailImage/`,
    DETAILS: `${API_BASE_URL}/peakagedetails/`,
    PRICE_RATES: `${API_BASE_URL}/priceRate/`,
    DATES_AND_PRICE: `${API_BASE_URL}/datesAndPrice/`,
    CANCELLATION_POLICY: `${API_BASE_URL}/createPolice/`,
    CANCELLATION_POLICY_ADD: `${API_BASE_URL}/Policy/`,
    TERMS_AND_CONDITION: `${API_BASE_URL}/terms&policy/`,
    PRESET_INCLUSION: `${API_BASE_URL}/presetInclusion/`,
    PRESET_EXCLUSION: `${API_BASE_URL}/presetExclusion/`,
    INCLUSION: `${API_BASE_URL}/inclusion/`,
    EXCLUSION: `${API_BASE_URL}/exclusion/`,
  },
  PREFERRED_LOCATIONS: {
    CITIES: `${API_BASE_URL}/preferredCity/`,
    COUNTRIES: `${API_BASE_URL}/preferredCountry/`,
  },
};

export default ApiRoutes;