export const countries = [
  { label: "Afghanistan", value: "97" },
  { label: "Albania", value: "43" },
  { label: "Algeria", value: "142" },
  { label: "Andorra", value: "44" },
  { label: "Angola", value: "143" },
  { label: "Antigua And Barbuda", value: "230" },
  { label: "Argentina", value: "29" },
  { label: "Armenia", value: "45" },
  { label: "Aruba", value: "231" },
  { label: "Australia", value: "196" },
  { label: "Austria", value: "46" },
  { label: "Azerbaijan", value: "47" },
  { label: "Bahamas", value: "3" },
  { label: "Bahrain", value: "98" },
  { label: "Bangladesh", value: "99" },
  { label: "Barbados", value: "4" },
  { label: "Belarus", value: "48" },
  { label: "Belgium", value: "49" },
  { label: "Belize", value: "5" },
  { label: "Benin", value: "144" },
  { label: "Bermuda", value: "6" },
  { label: "Bhutan", value: "100" },
  { label: "Bolivia", value: "30" },
  { label: "Bonaire, Sint Eustatius And Saba", value: "416" },
  { label: "Bosnia And Herzegovina", value: "50" },
  { label: "Botswana", value: "145" },
  { label: "Brazil", value: "31" },
  { label: "British Virgin Islands", value: "7" },
  { label: "Brunei", value: "101" },
  { label: "Bulgaria", value: "51" },
  { label: "Burkina Faso", value: "146" },
  { label: "Burundi", value: "147" },
  { label: "Cambodia", value: "102" },
  { label: "Cameroon", value: "148" },
  { label: "Canada", value: "2" },
  { label: "Cape Verde", value: "149" },
  { label: "Cayman Islands", value: "8" },
  { label: "Central African Republic", value: "150" },
  { label: "Chad", value: "151" },
  { label: "Chile", value: "32" },
  { label: "China", value: "103" },
  { label: "Colombia", value: "33" },
  { label: "Comoros", value: "402" },
  { label: "Cook Islands", value: "412" },
  { label: "Costa Rica", value: "9" },
  { label: "Croatia", value: "52" },
  { label: "Cuba", value: "10" },
  { label: "Curacao", value: "415" },
  { label: "Cyprus", value: "53" },
  { label: "Czech Republic", value: "54" },
  { label: "Democratic Republic Of The Congo", value: "153" },
  { label: "Denmark", value: "55" },
  { label: "Djibouti", value: "154" },
  { label: "Dominica", value: "11" },
  { label: "Dominican Republic", value: "12" },
  { label: "East Timor", value: "104" },
  { label: "Ecuador", value: "34" },
  { label: "Egypt", value: "155" },
  { label: "El Salvador", value: "13" },
  { label: "Equatorial Guinea", value: "156" },
  { label: "Eritrea", value: "157" },
  { label: "Estonia", value: "56" },
  { label: "Ethiopia", value: "158" },
  { label: "Falkland Islands", value: "35" },
  { label: "Fiji Islands", value: "198" },
  { label: "Finland", value: "57" },
  { label: "France", value: "58" },
  { label: "French Guiana", value: "36" },
  { label: "French Polynesia", value: "199" },
  { label: "Gabon", value: "159" },
  { label: "Gambia", value: "160" },
  { label: "Georgia", value: "59" },
  { label: "Germany", value: "60" },
  { label: "Ghana", value: "161" },
  { label: "Gibraltar", value: "61" },
  { label: "Greece", value: "62" },
  { label: "Greece Islands", value: "404" },
  { label: "Greenland", value: "14" },
  { label: "Grenada", value: "15" },
  { label: "Guadeloupe", value: "16" },
  { label: "Guam", value: "200" },
  { label: "Guatemala", value: "17" },
  { label: "Guernsey", value: "63" },
  { label: "Guinea", value: "162" },
  { label: "Guinea Bissau", value: "163" },
  { label: "Guyana", value: "37" },
  { label: "Haiti", value: "18" },
  { label: "Honduras", value: "19" },
  { label: "Hong Kong", value: "105" },
  { label: "Hungary", value: "64" },
  { label: "Iceland", value: "65" },
  { label: "India", value: "106" },
  { label: "Indonesia", value: "107" },
  { label: "Iran", value: "108" },
  { label: "Iraq", value: "109" },
  { label: "Ireland", value: "66" },
  { label: "Isle Of Man", value: "67" },
  { label: "Israel", value: "110" },
  { label: "Italy", value: "68" },
  { label: "Ivory Coast", value: "164" },
  { label: "Jamaica", value: "20" },
  { label: "Japan", value: "111" },
  { label: "Jersey", value: "69" },
  { label: "Jordan", value: "112" },
  { label: "Kazakhstan", value: "113" },
  { label: "Kenya", value: "165" },
  { label: "Kiribati", value: "201" },
  { label: "Kosovo", value: "70" },
  { label: "Kuwait", value: "114" },
  { label: "Kyrgyzstan", value: "115" },
  { label: "Laos", value: "116" },
  { label: "Latvia", value: "71" },
  { label: "Lebanon", value: "117" },
  { label: "Lesotho", value: "166" },
  { label: "Liberia", value: "167" },
  { label: "Libya", value: "168" },
  { label: "Liechtenstein", value: "72" },
  { label: "Lithuania", value: "73" },
  { label: "Luxembourg", value: "74" },
  { label: "Macau", value: "118" },
  { label: "Macedonia", value: "75" },
  { label: "Madagascar", value: "169" },
  { label: "Malawi", value: "170" },
  { label: "Malaysia", value: "119" },
  { label: "Maldives", value: "120" },
  { label: "Mali", value: "171" },
  { label: "Malta", value: "76" },
  { label: "Marshall Islands", value: "202" },
  { label: "Martinique", value: "21" },
  { label: "Mauritania", value: "172" },
  { label: "Mauritius", value: "173" },
  { label: "Mexico", value: "22" },
  { label: "Micronesia", value: "203" },
  { label: "Moldova", value: "77" },
  { label: "Monaco", value: "78" },
  { label: "Mongolia", value: "121" },
  { label: "Montenegro", value: "79" },
  { label: "Montserrat", value: "23" },
  { label: "Morocco", value: "174" },
  { label: "Mozambique", value: "175" },
  { label: "Myanmar (Burma)", value: "122" },
  { label: "Namibia", value: "176" },
  { label: "Nauru", value: "204" },
  { label: "Nepal", value: "123" },
  { label: "Netherlands", value: "80" },
  { label: "New Caledonia", value: "205" },
  { label: "New Zealand", value: "197" },
  { label: "Nicaragua", value: "24" },
  { label: "Niger", value: "177" },
  { label: "Nigeria", value: "178" },
  { label: "North Korea", value: "124" },
  { label: "Northern Cyprus", value: "411" },
  { label: "Northern Mariana Islands", value: "414" },
  { label: "Norway", value: "81" },
  { label: "Oman", value: "125" },
  { label: "Pakistan", value: "126" },
  { label: "Palestine", value: "228" },
  { label: "Panama", value: "25" },
  { label: "Papua New Guinea", value: "206" },
  { label: "Paraguay", value: "38" },
  { label: "Peru", value: "39" },
  { label: "Philippines", value: "127" },
  { label: "Poland", value: "82" },
  { label: "Portugal", value: "83" },
  { label: "Puerto Rico", value: "26" },
  { label: "Qatar", value: "128" },
  { label: "Republic Of The Congo", value: "152" },
  { label: "Reunion", value: "179" },
  { label: "Romania", value: "84" },
  { label: "Russia", value: "85" },
  { label: "Rwanda", value: "180" },
  { label: "Saint Barthelemy", value: "400" },
  { label: "Saint Kitts And Nevis", value: "413" },
  { label: "Saint Lucia", value: "401" },
  { label: "Samoa", value: "207" },
  { label: "San Marino", value: "86" },
  { label: "Sao Tome And Principe", value: "181" },
  { label: "Saudi Arabia", value: "129" },
  { label: "Senegal", value: "182" },
  { label: "Serbia", value: "87" },
  { label: "Seychelles", value: "183" },
  { label: "Sierra Leone", value: "184" },
  { label: "Singapore", value: "130" },
  { label: "Slovakia", value: "88" },
  { label: "Slovenia", value: "89" },
  { label: "Solomon Islands", value: "208" },
  { label: "Somalia", value: "185" },
  { label: "South Africa", value: "186" },
  { label: "South Korea", value: "131" },
  { label: "South Sudan", value: "403" },
  { label: "Spain", value: "90" },
  { label: "Sri Lanka", value: "132" },
  { label: "Sudan", value: "187" },
  { label: "Suriname", value: "40" },
  { label: "Swaziland", value: "188" },
  { label: "Sweden", value: "91" },
  { label: "Switzerland", value: "92" },
  { label: "Syria", value: "133" },
  { label: "Taiwan", value: "134" },
  { label: "Tajikistan", value: "135" },
  { label: "Tanzania", value: "189" },
  { label: "Thailand", value: "136" },
  { label: "Togo", value: "190" },
  { label: "Tonga", value: "209" },
  { label: "Trinidad And Tobago", value: "27" },
  { label: "Tunisia", value: "191" },
  { label: "Turkey", value: "93" },
  { label: "Turkmenistan", value: "137" },
  { label: "Turks And Caicos Islands", value: "410" },
  { label: "Tuvalu", value: "210" },
  { label: "Uganda", value: "192" },
  { label: "Ukraine", value: "94" },
  { label: "United Arab Emirates", value: "138" },
  { label: "United Kingdom", value: "95" },
  { label: "United States", value: "1" },
  { label: "United States Virgin Islands", value: "28" },
  { label: "Uruguay", value: "41" },
  { label: "Uzbekistan", value: "139" },
  { label: "Vanuatu", value: "211" },
  { label: "Vatican City", value: "96" },
  { label: "Venezuela", value: "42" },
  { label: "Vietnam", value: "140" },
  { label: "Wallis And Futuna", value: "212" },
  { label: "Western Sahara", value: "193" },
  { label: "Yemen", value: "141" },
  { label: "Zambia", value: "194" },
  { label: "Zimbabwe", value: "195" },
];






export const citiesByCountry = {
  97: [
    { label: "Kabul", value: "1" },
    { label: "Kandahar", value: "2" },
    { label: "Herat", value: "3" },
    { label: "Mazar-e-Sharif", value: "4" },
    { label: "Jalalabad", value: "5" },
    { label: "Kunduz", value: "6" },
    { label: "Ghazni", value: "7" },
    { label: "Bamyan", value: "8" },
    { label: "Farah", value: "9" },
    { label: "Pul-e-Khumri", value: "10" },
  ], // Cities for Afghanistan
  43: [
    { label: "Tirana", value: "1" },
    { label: "Durrës", value: "2" },
    { label: "Vlorë", value: "3" },
    { label: "Shkodër", value: "4" },
    { label: "Fier", value: "5" },
    { label: "Korçë", value: "6" },
    { label: "Elbasan", value: "7" },
    { label: "Berat", value: "8" },
    { label: "Lushnjë", value: "9" },
    { label: "Kavajë", value: "10" },
  ],
  142: [
    { label: "Algiers", value: "1" },
    { label: "Oran", value: "2" },
    { label: "Constantine", value: "3" },
    { label: "Annaba", value: "4" },
    { label: "Blida", value: "5" },
    { label: "Batna", value: "6" },
    { label: "Djelfa", value: "7" },
    { label: "Sétif", value: "8" },
    { label: "Biskra", value: "9" },
    { label: "Tlemcen", value: "10" },
  ],

  44: [
    { label: "Andorra la Vella", value: "1" },
    { label: "Escaldes-Engordany", value: "2" },
    { label: "Encamp", value: "3" },
    { label: "Sant Julià de Lòria", value: "4" },
    { label: "La Massana", value: "5" },
    { label: "Canillo", value: "6" },
    { label: "Ordino", value: "7" },
  ],
  143: [
    { label: "Luanda", value: "1" },
    { label: "Huambo", value: "2" },
    { label: "Lobito", value: "3" },
    { label: "Benguela", value: "4" },
    { label: "Kuito", value: "5" },
    { label: "Malanje", value: "6" },
    { label: "Namibe", value: "7" },
    { label: "Soyo", value: "8" },
    { label: "Cabinda", value: "9" },
    { label: "Uíge", value: "10" },
  ],
  230: [
    { label: "St. John's", value: "1" },
    { label: "All Saints", value: "2" },
    { label: "Liberta", value: "3" },
    { label: "Bolans", value: "4" },
    { label: "Piggotts", value: "5" },
    { label: "Codrington", value: "6" },
    { label: "Parham", value: "7" },
    { label: "Swetes", value: "8" },
    { label: "Saint Paul’s", value: "9" },
    { label: "Falmouth", value: "10" },
    // Add more towns or cities as needed
  ],
  29: [
    { label: "Buenos Aires", value: "1" },
    { label: "Córdoba", value: "2" },
    { label: "Rosario", value: "3" },
    { label: "Mendoza", value: "4" },
    { label: "San Miguel de Tucumán", value: "5" },
    { label: "La Plata", value: "6" },
    { label: "Mar del Plata", value: "7" },
    { label: "Salta", value: "8" },
    { label: "Santa Fe", value: "9" },
    { label: "San Juan", value: "10" },
  ],

  45: [
    { label: "Yerevan", value: "1" },
    { label: "Gyumri", value: "2" },
    { label: "Vanadzor", value: "3" },
    { label: "Ejmiatsin", value: "4" },
    { label: "Hrazdan", value: "5" },
    { label: "Abovyan", value: "6" },
    { label: "Kapan", value: "7" },
    { label: "Ararat", value: "8" },
    { label: "Armavir", value: "9" },
    { label: "Gavar", value: "10" },
  ],

  231: [
    { label: "Oranjestad", value: "1" },
    { label: "San Nicolas", value: "2" },
    { label: "Noord", value: "3" },
    { label: "Paradera", value: "4" },
    { label: "Savaneta", value: "5" },
    { label: "Santa Cruz", value: "6" },
    { label: "Oranjestad West", value: "7" },
    { label: "Tanki Leendert", value: "8" },
    { label: "Angochi", value: "9" },
    { label: "Pos Chiquito", value: "10" },
  ],
  196: [
    { label: "Sydney", value: "1" },
    { label: "Melbourne", value: "2" },
    { label: "Brisbane", value: "3" },
    { label: "Perth", value: "4" },
    { label: "Adelaide", value: "5" },
    { label: "Gold Coast", value: "6" },
    { label: "Canberra", value: "7" },
    { label: "Newcastle", value: "8" },
    { label: "Hobart", value: "9" },
    { label: "Darwin", value: "10" },
  ],

  46: [
    { label: "Vienna", value: "1" },
    { label: "Graz", value: "2" },
    { label: "Linz", value: "3" },
    { label: "Salzburg", value: "4" },
    { label: "Innsbruck", value: "5" },
    { label: "Klagenfurt", value: "6" },
    { label: "Villach", value: "7" },
    { label: "Wels", value: "8" },
    { label: "Sankt Pölten", value: "9" },
    { label: "Dornbirn", value: "10" },
  ],

  47: [
    { label: "Baku", value: "1" },
    { label: "Ganja", value: "2" },
    { label: "Sumqayit", value: "3" },
    { label: "Mingachevir", value: "4" },
    { label: "Lankaran", value: "5" },
    { label: "Nakhchivan", value: "6" },
    { label: "Sheki", value: "7" },
    { label: "Shirvan", value: "8" },
    { label: "Yevlakh", value: "9" },
    { label: "Agdam", value: "10" },
  ],

  3: [
    { label: "Nassau", value: "1" },
    { label: "Freeport", value: "2" },
    { label: "Lucaya", value: "3" },
    { label: "West End", value: "4" },
    { label: "Cooper's Town", value: "5" },
    { label: "Marsh Harbour", value: "6" },
    { label: "High Rock", value: "7" },
    { label: "Andros Town", value: "8" },
    { label: "Clarence Town", value: "9" },
    { label: "Dunmore Town", value: "10" },
  ],

  98: [
    { label: "Manama", value: "1" },
    { label: "Riffa", value: "2" },
    { label: "Muharraq", value: "3" },
    { label: "Hamad Town", value: "4" },
    { label: "A'ali", value: "5" },
    { label: "Isa Town", value: "6" },
    { label: "Sitra", value: "7" },
    { label: "Jidhafs", value: "8" },
    { label: "Al-Malikiyah", value: "9" },
    { label: "Tubli", value: "10" },
  ],

  99: [
    { label: "Dhaka", value: "1" },
    { label: "Chittagong", value: "2" },
    { label: "Khulna", value: "3" },
    { label: "Rajshahi", value: "4" },
    { label: "Comilla", value: "5" },
    { label: "Sylhet", value: "6" },
    { label: "Barisal", value: "7" },
    { label: "Rangpur", value: "8" },
    { label: "Narayanganj", value: "9" },
    { label: "Dinajpur", value: "10" },
  ],

  4: [
    { label: "Bridgetown", value: "1" },
    { label: "Speightstown", value: "2" },
    { label: "Oistins", value: "3" },
    { label: "Holetown", value: "4" },
    { label: "Crane", value: "5" },
    { label: "Black Rock", value: "6" },
    { label: "Bathsheba", value: "7" },
    { label: "Greenland", value: "8" },
    { label: "Checker Hall", value: "9" },
    { label: "Flat Rock", value: "10" },
  ],
  48: [
    { label: "Minsk", value: "1" },
    { label: "Homyel", value: "2" },
    { label: "Mahilyow", value: "3" },
    { label: "Vitebsk", value: "4" },
    { label: "Hrodna", value: "5" },
    { label: "Brest", value: "6" },
    { label: "Babruysk", value: "7" },
    { label: "Baranavichy", value: "8" },
    { label: "Pinsk", value: "9" },
    { label: "Orsha", value: "10" },
  ],

  49: [
    { label: "Brussels", value: "1" },
    { label: "Antwerp", value: "2" },
    { label: "Ghent", value: "3" },
    { label: "Charleroi", value: "4" },
    { label: "Liege", value: "5" },
    { label: "Bruges", value: "6" },
    { label: "Namur", value: "7" },
    { label: "Leuven", value: "8" },
    { label: "Mons", value: "9" },
    { label: "Aalst", value: "10" },
  ],

  5: [
    { label: "Belmopan", value: "1" },
    { label: "Belize City", value: "2" },
    { label: "San Ignacio", value: "3" },
    { label: "Orange Walk", value: "4" },
    { label: "Dangriga", value: "5" },
    { label: "Corozal Town", value: "6" },
    { label: "Punta Gorda", value: "7" },
    { label: "Benque Viejo del Carmen", value: "8" },
    { label: "Stann Creek Town", value: "9" },
    { label: "San Pedro Town", value: "10" },
  ],

  144: [
    { label: "Porto-Novo", value: "1" },
    { label: "Cotonou", value: "2" },
    { label: "Parakou", value: "3" },
    { label: "Djougou", value: "4" },
    { label: "Ouidah", value: "5" },
    { label: "Abomey-Calavi", value: "6" },
    { label: "Natitingou", value: "7" },
    { label: "Lokossa", value: "8" },
    { label: "Bohicon", value: "9" },
    { label: "Kandi", value: "10" },
  ],

  6: [
    { label: "Hamilton", value: "1" },
    { label: "Saint George", value: "2" },
    { label: "Somerset Village", value: "3" },
    { label: "St. George's", value: "4" },
    { label: "Hamilton Parish", value: "5" },
    { label: "Sandys Parish", value: "6" },
    { label: "Smith's Parish", value: "7" },
    { label: "Devonshire Parish", value: "8" },
    { label: "Paget Parish", value: "9" },
    { label: "Pembroke Parish", value: "10" },
  ],

  100: [
    { label: "Thimphu", value: "1" },
    { label: "Phuntsholing", value: "2" },
    { label: "Paro", value: "3" },
    { label: "Punakha", value: "4" },
    { label: "Jakar", value: "5" },
    { label: "Gelephu", value: "6" },
    { label: "Samdrup Jongkhar", value: "7" },
    { label: "Wangdue Phodrang", value: "8" },
    { label: "Trashigang", value: "9" },
    { label: "Bumthang", value: "10" },
  ],

  30: [
    { label: "Sucre", value: "1" },
    { label: "La Paz", value: "2" },
    { label: "Santa Cruz de la Sierra", value: "3" },
    { label: "Cochabamba", value: "4" },
    { label: "Oruro", value: "5" },
    { label: "Tarija", value: "6" },
    { label: "Potosi", value: "7" },
    { label: "Sacaba", value: "8" },
    { label: "Montero", value: "9" },
    { label: "Quillacollo", value: "10" },
  ],

  416: [
    { label: "Kralendijk", value: "1" },
    { label: "Oranjestad", value: "2" },
    { label: "The Bottom", value: "3" },
    { label: "Windwardside", value: "4" },
    { label: "Upper Hell's Gate", value: "5" },
    { label: "Lower Hell's Gate", value: "6" },
    { label: "St. John's", value: "7" },
    { label: "St. Paul's", value: "8" },
    { label: "St. John's", value: "9" },
    { label: "Lower Prince's Quarter", value: "10" },
  ],

  50: [
    { label: "Sarajevo", value: "1" },
    { label: "Banja Luka", value: "2" },
    { label: "Tuzla", value: "3" },
    { label: "Zenica", value: "4" },
    { label: "Mostar", value: "5" },
    { label: "Bijeljina", value: "6" },
    { label: "Prijedor", value: "7" },
    { label: "Brcko", value: "8" },
    { label: "Trebinje", value: "9" },
    { label: "Cazin", value: "10" },
  ],

  145: [
    { label: "Gaborone", value: "1" },
    { label: "Francistown", value: "2" },
    { label: "Molepolole", value: "3" },
    { label: "Serowe", value: "4" },
    { label: "Selibe Phikwe", value: "5" },
    { label: "Maun", value: "6" },
    { label: "Kanye", value: "7" },
    { label: "Mahalapye", value: "8" },
    { label: "Mogoditshane", value: "9" },
    { label: "Lobatse", value: "10" },
  ],

  31: [
    { label: "Sao Paulo", value: "1" },
    { label: "Rio de Janeiro", value: "2" },
    { label: "Salvador", value: "3" },
    { label: "Brasilia", value: "4" },
    { label: "Fortaleza", value: "5" },
    { label: "Belo Horizonte", value: "6" },
    { label: "Manaus", value: "7" },
    { label: "Curitiba", value: "8" },
    { label: "Recife", value: "9" },
    { label: "Porto Alegre", value: "10" },
  ],

  7: [
    { label: "Road Town", value: "1" },
    { label: "Tortola", value: "2" },
    { label: "Spanish Town", value: "3" },
    { label: "Charlotte Amalie", value: "4" },
    { label: "West End", value: "5" },
    { label: "East End", value: "6" },
    { label: "Virgin Gorda", value: "7" },
    { label: "Jost Van Dyke", value: "8" },
    { label: "Anegada", value: "9" },
    { label: "Duff's Bottom", value: "10" },
  ],

  101: [
    { label: "Bandar Seri Begawan", value: "1" },
    { label: "Kuala Belait", value: "2" },
    { label: "Seria", value: "3" },
    { label: "Tutong", value: "4" },
    { label: "Bangar", value: "5" },
    { label: "Jerudong", value: "6" },
    { label: "Subok", value: "7" },
    { label: "Serasa", value: "8" },
    { label: "Lumapas", value: "9" },
    { label: "Pekan Tutong", value: "10" },
  ],

  51: [
    { label: "Sofia", value: "1" },
    { label: "Plovdiv", value: "2" },
    { label: "Varna", value: "3" },
    { label: "Burgas", value: "4" },
    { label: "Ruse", value: "5" },
    { label: "Stara Zagora", value: "6" },
    { label: "Pleven", value: "7" },
    { label: "Sliven", value: "8" },
    { label: "Dobrich", value: "9" },
    { label: "Shumen", value: "10" },
  ],

  146: [
    { label: "Ouagadougou", value: "1" },
    { label: "Bobo-Dioulasso", value: "2" },
    { label: "Koudougou", value: "3" },
    { label: "Ouahigouya", value: "4" },
    { label: "Banfora", value: "5" },
    { label: "Dedougou", value: "6" },
    { label: "Kaya", value: "7" },
    { label: "Tenkodogo", value: "8" },
    { label: "Fada N'gourma", value: "9" },
    { label: "Hounde", value: "10" },
  ],

  147: [
    { label: "Bujumbura", value: "1" },
    { label: "Muyinga", value: "2" },
    { label: "Gitega", value: "3" },
    { label: "Ruyigi", value: "4" },
    { label: "Ngozi", value: "5" },
    { label: "Bururi", value: "6" },
    { label: "Kirundo", value: "7" },
    { label: "Makamba", value: "8" },
    { label: "Kayanza", value: "9" },
    { label: "Muramvya", value: "10" },
  ],
  102: [
    { label: "Phnom Penh", value: "1" },
    { label: "Siem Reap", value: "2" },
    { label: "Battambang", value: "3" },
    { label: "Sihanoukville", value: "4" },
    { label: "Kampong Cham", value: "5" },
    { label: "Krong Preah Sihanouk", value: "6" },
    { label: "Kampong Speu", value: "7" },
    { label: "Kampong Thom", value: "8" },
    { label: "Krong Ta Khmau", value: "9" },
    { label: "Kampot", value: "10" },
  ],

  148: [
    { label: "Yaounde", value: "1" },
    { label: "Douala", value: "2" },
    { label: "Garoua", value: "3" },
    { label: "Bamenda", value: "4" },
    { label: "Maroua", value: "5" },
    { label: "Bafoussam", value: "6" },
    { label: "Ngaoundere", value: "7" },
    { label: "Bertoua", value: "8" },
    { label: "Edea", value: "9" },
    { label: "Loum", value: "10" },
  ],

  2: [
    { label: "Toronto", value: "1" },
    { label: "Montreal", value: "2" },
    { label: "Vancouver", value: "3" },
    { label: "Calgary", value: "4" },
    { label: "Edmonton", value: "5" },
    { label: "Ottawa", value: "6" },
    { label: "Quebec City", value: "7" },
    { label: "Winnipeg", value: "8" },
    { label: "Hamilton", value: "9" },
    { label: "Kitchener", value: "10" },
  ],

  149: [
    { label: "Praia", value: "1" },
    { label: "Mindelo", value: "2" },
    { label: "Santa Maria", value: "3" },
    { label: "Assomada", value: "4" },
    { label: "Tarrafal", value: "5" },
    { label: "Pedra Badejo", value: "6" },
    { label: "Porto Novo", value: "7" },
    { label: "Vila do Maio", value: "8" },
    { label: "Cidade Velha", value: "9" },
    { label: "Vila do Porto Ingles", value: "10" },
  ],

  8: [
    { label: "George Town", value: "1" },
    { label: "West Bay", value: "2" },
    { label: "Bodden Town", value: "3" },
    { label: "East End", value: "4" },
    { label: "North Side", value: "5" },
    { label: "Savannah", value: "6" },
    { label: "Stake Bay", value: "7" },
    { label: "Hell", value: "8" },
    { label: "Newlands", value: "9" },
    { label: "Barefoot Beach", value: "10" },
  ],

  150: [
    { label: "Bangui", value: "1" },
    { label: "Bimbo", value: "2" },
    { label: "Mbaiki", value: "3" },
    { label: "Berberati", value: "4" },
    { label: "Kaga-Bandoro", value: "5" },
    { label: "Bozoum", value: "6" },
    { label: "Carnot", value: "7" },
    { label: "Sibut", value: "8" },
    { label: "Bambari", value: "9" },
    { label: "Bria", value: "10" },
  ],

  151: [
    { label: "N'Djamena", value: "1" },
    { label: "Moundou", value: "2" },
    { label: "Sarh", value: "3" },
    { label: "Abéché", value: "4" },
    { label: "Kelo", value: "5" },
    { label: "Koumra", value: "6" },
    { label: "Pala", value: "7" },
    { label: "Am Timan", value: "8" },
    { label: "Bongor", value: "9" },
    { label: "Mongo", value: "10" },
  ],

  32: [
    { label: "Santiago", value: "1" },
    { label: "Valparaiso", value: "2" },
    { label: "Viña del Mar", value: "3" },
    { label: "Concepcion", value: "4" },
    { label: "Antofagasta", value: "5" },
    { label: "Puente Alto", value: "6" },
    { label: "Valdivia", value: "7" },
    { label: "Talcahuano", value: "8" },
    { label: "Temuco", value: "9" },
    { label: "La Serena", value: "10" },
  ],

  103: [
    { label: "Shanghai", value: "1" },
    { label: "Beijing", value: "2" },
    { label: "Guangzhou", value: "3" },
    { label: "Shenzhen", value: "4" },
    { label: "Wuhan", value: "5" },
    { label: "Chengdu", value: "6" },
    { label: "Nanjing", value: "7" },
    { label: "Chongqing", value: "8" },
    { label: "Hangzhou", value: "9" },
    { label: "Xi'an", value: "10" },
  ],

  33: [
    { label: "Bogota", value: "1" },
    { label: "Medellin", value: "2" },
    { label: "Cali", value: "3" },
    { label: "Barranquilla", value: "4" },
    { label: "Cartagena", value: "5" },
    { label: "Cucuta", value: "6" },
    { label: "Bucaramanga", value: "7" },
    { label: "Pereira", value: "8" },
    { label: "Santa Marta", value: "9" },
    { label: "Ibague", value: "10" },
  ],

  402: [
    { label: "Moroni", value: "1" },
    { label: "Moutsamoudou", value: "2" },
    { label: "Fomboni", value: "3" },
    { label: "Domoni", value: "4" },
    { label: "Sima", value: "5" },
    { label: "Ouani", value: "6" },
    { label: "Mirontsi", value: "7" },
    { label: "Itsandra", value: "8" },
    { label: "Tsidje", value: "9" },
    { label: "Nyembwa", value: "10" },
  ],

  412: [
    { label: "Avarua", value: "1" },
    { label: "Arutanga", value: "2" },
    { label: "Amuri", value: "3" },
    { label: "Atiu", value: "4" },
    { label: "Mangaia", value: "5" },
    { label: "Mauke", value: "6" },
    { label: "Mitiaro", value: "7" },
    { label: "Nassau", value: "8" },
    { label: "Nikao", value: "9" },
    { label: "Oneroa", value: "10" },
  ],

  9: [
    { label: "San Jose", value: "1" },
    { label: "Limon", value: "2" },
    { label: "San Francisco", value: "3" },
    { label: "Alajuela", value: "4" },
    { label: "Liberia", value: "5" },
    { label: "Heredia", value: "6" },
    { label: "Puntarenas", value: "7" },
    { label: "Cinco Esquinas", value: "8" },
    { label: "Desamparados", value: "9" },
    { label: "Curridabat", value: "10" },
  ],

  52: [
    { label: "Zagreb", value: "1" },
    { label: "Split", value: "2" },
    { label: "Rijeka", value: "3" },
    { label: "Osijek", value: "4" },
    { label: "Zadar", value: "5" },
    { label: "Slavonski Brod", value: "6" },
    { label: "Pula", value: "7" },
    { label: "Karlovac", value: "8" },
    { label: "Varazdin", value: "9" },
    { label: "Sibenik", value: "10" },
  ],

  10: [
    { label: "Havana", value: "1" },
    { label: "Santiago de Cuba", value: "2" },
    { label: "Camaguey", value: "3" },
    { label: "Holguin", value: "4" },
    { label: "Santa Clara", value: "5" },
    { label: "Guantanamo", value: "6" },
    { label: "Bayamo", value: "7" },
    { label: "Las Tunas", value: "8" },
    { label: "Cienfuegos", value: "9" },
    { label: "Pinar del Rio", value: "10" },
  ],

  415: [
    { label: "Willemstad", value: "1" },
    { label: "Sint Michiel Liber", value: "2" },
    { label: "Dorp Soto", value: "3" },
    { label: "Dorp Sint Willebrordus", value: "4" },
    { label: "Groot Sint Joris", value: "5" },
    { label: "Dorp Barber", value: "6" },
    { label: "Dorp Westpunt", value: "7" },
    { label: "Dorp Tera Kora", value: "8" },
    { label: "Dorp Antriol", value: "9" },
    { label: "Nieuwpoort", value: "10" },
  ],
  53: [
    { label: "Nicosia", value: "1" },
    { label: "Limassol", value: "2" },
    { label: "Larnaca", value: "3" },
    { label: "Famagusta", value: "4" },
    { label: "Paphos", value: "5" },
    { label: "Kyrenia", value: "6" },
    { label: "Protaras", value: "7" },
    { label: "Ayia Napa", value: "8" },
    { label: "Polis", value: "9" },
    { label: "Deryneia", value: "10" },
  ],

  54: [
    { label: "Prague", value: "1" },
    { label: "Brno", value: "2" },
    { label: "Ostrava", value: "3" },
    { label: "Plzen", value: "4" },
    { label: "Liberec", value: "5" },
    { label: "Olomouc", value: "6" },
    { label: "Usti nad Labem", value: "7" },
    { label: "Hradec Kralove", value: "8" },
    { label: "Pardubice", value: "9" },
    { label: "Zlin", value: "10" },
  ],

  153: [
    { label: "Kinshasa", value: "1" },
    { label: "Lubumbashi", value: "2" },
    { label: "Mbuji-Mayi", value: "3" },
    { label: "Kananga", value: "4" },
    { label: "Kisangani", value: "5" },
    { label: "Bukavu", value: "6" },
    { label: "Tshikapa", value: "7" },
    { label: "Matadi", value: "8" },
    { label: "Mbandaka", value: "9" },
    { label: "Beni", value: "10" },
  ],

  55: [
    { label: "Copenhagen", value: "1" },
    { label: "Aarhus", value: "2" },
    { label: "Odense", value: "3" },
    { label: "Aalborg", value: "4" },
    { label: "Esbjerg", value: "5" },
    { label: "Randers", value: "6" },
    { label: "Kolding", value: "7" },
    { label: "Horsens", value: "8" },
    { label: "Vejle", value: "9" },
    { label: "Roskilde", value: "10" },
  ],

  154: [
    { label: "Djibouti", value: "1" },
    { label: "Ali Sabieh", value: "2" },
    { label: "Tadjoura", value: "3" },
    { label: "Obock", value: "4" },
    { label: "Dikhil", value: "5" },
    { label: "Arta", value: "6" },
    { label: "Holhol", value: "7" },
    { label: "Loyada", value: "8" },
    { label: "Ali Adde", value: "9" },
    { label: "Ghoubet", value: "10" },
  ],

  11: [
    { label: "Roseau", value: "1" },
    { label: "Portsmouth", value: "2" },
    { label: "Marigot", value: "3" },
    { label: "Berekua", value: "4" },
    { label: "Saint Joseph", value: "5" },
    { label: "Wesley", value: "6" },
    { label: "Mahaut", value: "7" },
    { label: "Salybia", value: "8" },
    { label: "Castle Bruce", value: "9" },
    { label: "La Plaine", value: "10" },
  ],

  12: [
    { label: "Santo Domingo", value: "1" },
    { label: "Santiago", value: "2" },
    { label: "La Romana", value: "3" },
    { label: "San Pedro de Macoris", value: "4" },
    { label: "San Francisco de Macoris", value: "5" },
    { label: "Salvaleon de Higuey", value: "6" },
    { label: "Puerto Plata", value: "7" },
    { label: "San Cristobal", value: "8" },
    { label: "La Vega", value: "9" },
    { label: "Barahona", value: "10" },
  ],

  104: [
    { label: "Dili", value: "1" },
    { label: "Aileu", value: "2" },
    { label: "Same", value: "3" },
    { label: "Baucau", value: "4" },
    { label: "Suai", value: "5" },
    { label: "Liquica", value: "6" },
    { label: "Gleno", value: "7" },
    { label: "Ainaro", value: "8" },
    { label: "Viqueque", value: "9" },
    { label: "Manatuto", value: "10" },
  ],

  34: [
    { label: "Quito", value: "1" },
    { label: "Guayaquil", value: "2" },
    { label: "Cuenca", value: "3" },
    { label: "Santo Domingo", value: "4" },
    { label: "Machala", value: "5" },
    { label: "Manta", value: "6" },
    { label: "Duran", value: "7" },
    { label: "Ambato", value: "8" },
    { label: "Ibarra", value: "9" },
    { label: "Quevedo", value: "10" },
  ],

  155: [
    { label: "Cairo", value: "1" },
    { label: "Alexandria", value: "2" },
    { label: "Giza", value: "3" },
    { label: "Shubra El Kheima", value: "4" },
    { label: "Port Said", value: "5" },
    { label: "Suez", value: "6" },
    { label: "Luxor", value: "7" },
    { label: "El Mahalla El Kubra", value: "8" },
    { label: "Asyut", value: "9" },
    { label: "Tanta", value: "10" },
  ],
  13: [
    { label: "San Salvador", value: "1" },
    { label: "Santa Ana", value: "2" },
    { label: "San Miguel", value: "3" },
    { label: "Apopa", value: "4" },
    { label: "Mejicanos", value: "5" },
    { label: "Santa Tecla", value: "6" },
    { label: "Ilopango", value: "7" },
    { label: "San Martin", value: "8" },
    { label: "Soyapango", value: "9" },
    { label: "Cojutepeque", value: "10" },
  ],

  156: [
    { label: "Malabo", value: "1" },
    { label: "Bata", value: "2" },
    { label: "Ebebiyin", value: "3" },
    { label: "Aconibe", value: "4" },
    { label: "Anisoc", value: "5" },
    { label: "Luba", value: "6" },
    { label: "Evinayong", value: "7" },
    { label: "Mongomo", value: "8" },
    { label: "Mikomeseng", value: "9" },
    { label: "Rebola", value: "10" },
  ],

  157: [
    { label: "Asmara", value: "1" },
    { label: "Keren", value: "2" },
    { label: "Massawa", value: "3" },
    { label: "Assab", value: "4" },
    { label: "Mendefera", value: "5" },
    { label: "Barentu", value: "6" },
    { label: "Adi Keyh", value: "7" },
    { label: "Ak'ordat", value: "8" },
    { label: "Teseney", value: "9" },
    { label: "Agordat", value: "10" },
  ],

  56: [
    { label: "Tallinn", value: "1" },
    { label: "Tartu", value: "2" },
    { label: "Narva", value: "3" },
    { label: "Parnu", value: "4" },
    { label: "Kohtla-Jarve", value: "5" },
    { label: "Viljandi", value: "6" },
    { label: "Rakvere", value: "7" },
    { label: "Maardu", value: "8" },
    { label: "Sillamae", value: "9" },
    { label: "Voru", value: "10" },
  ],

  158: [
    { label: "Addis Ababa", value: "1" },
    { label: "Dire Dawa", value: "2" },
    { label: "Mekele", value: "3" },
    { label: "Gondar", value: "4" },
    { label: "Hawassa", value: "5" },
    { label: "Bahir Dar", value: "6" },
    { label: "Dessie", value: "7" },
    { label: "Jimma", value: "8" },
    { label: "Jijiga", value: "9" },
    { label: "Shashamane", value: "10" },
  ],

  35: [
    { label: "Stanley", value: "1" },
  ],

  198: [
    { label: "Suva", value: "1" },
    { label: "Lautoka", value: "2" },
    { label: "Nadi", value: "3" },
    { label: "Labasa", value: "4" },
    { label: "Ba", value: "5" },
    { label: "Levuka", value: "6" },
    { label: "Savusavu", value: "7" },
    { label: "Nasinu", value: "8" },
    { label: "Nausori", value: "9" },
    { label: "Sigatoka", value: "10" },
  ],

  57: [
    { label: "Helsinki", value: "1" },
    { label: "Espoo", value: "2" },
    { label: "Tampere", value: "3" },
    { label: "Vantaa", value: "4" },
    { label: "Oulu", value: "5" },
    { label: "Turku", value: "6" },
    { label: "Jyvaskyla", value: "7" },
    { label: "Lahti", value: "8" },
    { label: "Kuopio", value: "9" },
    { label: "Pori", value: "10" },
  ],

  58: [
    { label: "Paris", value: "1" },
    { label: "Marseille", value: "2" },
    { label: "Lyon", value: "3" },
    { label: "Toulouse", value: "4" },
    { label: "Nice", value: "5" },
    { label: "Nantes", value: "6" },
    { label: "Strasbourg", value: "7" },
    { label: "Montpellier", value: "8" },
    { label: "Bordeaux", value: "9" },
    { label: "Lille", value: "10" },
  ],

  36: [
    { label: "Cayenne", value: "1" },
    { label: "Matoury", value: "2" },
    { label: "Kourou", value: "3" },
    { label: "Saint-Laurent-du-Maroni", value: "4" },
    { label: "Remire-Montjoly", value: "5" },
    { label: "Cayenne", value: "6" },
    { label: "Macouria", value: "7" },
    { label: "Mana", value: "8" },
    { label: "Apatou", value: "9" },
    { label: "Grand-Santi", value: "10" },
  ],

  199: [
    { label: "Papeete", value: "1" },
    { label: "Faaa", value: "2" },
    { label: "Pirae", value: "3" },
    { label: "Mahina", value: "4" },
    { label: "Paea", value: "5" },
    { label: "Punaauia", value: "6" },
    { label: "Arue", value: "7" },
    { label: "Paea", value: "8" },
    { label: "Pirae", value: "9" },
    { label: "Punaauia", value: "10" },
  ],

  159: [
    { label: "Libreville", value: "1" },
    { label: "Port-Gentil", value: "2" },
    { label: "Franceville", value: "3" },
    { label: "Oyem", value: "4" },
    { label: "Moanda", value: "5" },
    { label: "Mouila", value: "6" },
    { label: "Lambaréné", value: "7" },
    { label: "Tchibanga", value: "8" },
    { label: "Koulamoutou", value: "9" },
    { label: "Bitam", value: "10" },
  ],

  160: [
    { label: "Banjul", value: "1" },
    { label: "Serekunda", value: "2" },
    { label: "Brikama", value: "3" },
    { label: "Bakau", value: "4" },
    { label: "Banjul", value: "5" },
    { label: "Farafenni", value: "6" },
    { label: "Lamin", value: "7" },
    { label: "Sukuta", value: "8" },
    { label: "Basse Santa Su", value: "9" },
    { label: "Gunjur", value: "10" },
  ],

  161: [
    { label: "Tbilisi", value: "1" },
    { label: "Kutaisi", value: "2" },
    { label: "Batumi", value: "3" },
    { label: "Rustavi", value: "4" },
    { label: "Gori", value: "5" },
    { label: "Zugdidi", value: "6" },
    { label: "Poti", value: "7" },
    { label: "Samtredia", value: "8" },
    { label: "Khashuri", value: "9" },
    { label: "Senaki", value: "10" },
  ],

  60: [
    { label: "Berlin", value: "1" },
    { label: "Hamburg", value: "2" },
    { label: "Munich", value: "3" },
    { label: "Cologne", value: "4" },
    { label: "Frankfurt", value: "5" },
    { label: "Stuttgart", value: "6" },
    { label: "Dusseldorf", value: "7" },
    { label: "Dortmund", value: "8" },
    { label: "Essen", value: "9" },
    { label: "Leipzig", value: "10" },
  ],
  61: [
    { label: "Gibraltar", value: "1" },
  ],

  62: [
    { label: "Athens", value: "1" },
    { label: "Thessaloniki", value: "2" },
    { label: "Patras", value: "3" },
    { label: "Heraklion", value: "4" },
    { label: "Larissa", value: "5" },
    { label: "Volos", value: "6" },
    { label: "Ioannina", value: "7" },
    { label: "Chania", value: "8" },
    { label: "Rhodes", value: "9" },
    { label: "Sparta", value: "10" },
  ],

  404: [
    { label: "Rhodes", value: "1" },
    { label: "Crete", value: "2" },
    { label: "Mykonos", value: "3" },
    { label: "Santorini", value: "4" },
    { label: "Corfu", value: "5" },
    { label: "Zakynthos", value: "6" },
    { label: "Kos", value: "7" },
    { label: "Lesbos", value: "8" },
    { label: "Chios", value: "9" },
    { label: "Samos", value: "10" },
  ],

  14: [
    { label: "Nuuk", value: "1" },
    { label: "Sisimiut", value: "2" },
    { label: "Ilulissat", value: "3" },
    { label: "Qaqortoq", value: "4" },
    { label: "Aasiaat", value: "5" },
    { label: "Maniitsoq", value: "6" },
    { label: "Narsaq", value: "7" },
    { label: "Tasiilaq", value: "8" },
    { label: "Paamiut", value: "9" },
    { label: "Kangerlussuaq", value: "10" },
  ],

  15: [
    { label: "St. George's", value: "1" },
    { label: "Gouyave", value: "2" },
    { label: "Grenville", value: "3" },
    { label: "Victoria", value: "4" },
    { label: "Sauteurs", value: "5" },
    { label: "Hillsborough", value: "6" },
    { label: "Birch Grove", value: "7" },
    { label: "La Sagesse", value: "8" },
    { label: "Westerhall", value: "9" },
    { label: "Belmont", value: "10" },
  ],

  16: [
    { label: "Basse-Terre", value: "1" },
    { label: "Pointe-à-Pitre", value: "2" },
    { label: "Les Abymes", value: "3" },
    { label: "Baie-Mahault", value: "4" },
    { label: "Le Gosier", value: "5" },
    { label: "Sainte-Anne", value: "6" },
    { label: "Petit-Bourg", value: "7" },
    { label: "Sainte-Rose", value: "8" },
    { label: "Capesterre-Belle-Eau", value: "9" },
    { label: "Gourbeyre", value: "10" },
  ],

  200: [
    { label: "Hagåtña", value: "1" },
    { label: "Tamuning", value: "2" },
    { label: "Dededo", value: "3" },
    { label: "Yigo", value: "4" },
    { label: "Mangilao", value: "5" },
    { label: "Barrigada", value: "6" },
    { label: "Santa Rita", value: "7" },
    { label: "Agat", value: "8" },
    { label: "Yona", value: "9" },
    { label: "Chalan Pago-Ordot", value: "10" },
  ],

  17: [
    { label: "Guatemala City", value: "1" },
    { label: "Mixco", value: "2" },
    { label: "Villa Nueva", value: "3" },
    { label: "Petapa", value: "4" },
    { label: "San Juan Sacatepequez", value: "5" },
    { label: "Quetzaltenango", value: "6" },
    { label: "Escuintla", value: "7" },
    { label: "Jalapa", value: "8" },
    { label: "Chiquimula", value: "9" },
    { label: "Huehuetenango", value: "10" },
  ],

  63: [
    { label: "St. Peter Port", value: "1" },
    { label: "St. Sampson", value: "2" },
    { label: "St. Martin", value: "3" },
    { label: "St. Andrew", value: "4" },
    { label: "St. Pierre du Bois", value: "5" },
    { label: "Castel", value: "6" },
    { label: "St. Ouen", value: "7" },
    { label: "St. Martin", value: "8" },
    { label: "St. Saviour", value: "9" },
    { label: "Torteval", value: "10" },
  ],

  162: [
    { label: "Conakry", value: "1" },
    { label: "Nzérékoré", value: "2" },
    { label: "Kindia", value: "3" },
    { label: "Kankan", value: "4" },
    { label: "Gueckedou", value: "5" },
    { label: "Kamsar", value: "6" },
    { label: "Kissidougou", value: "7" },
    { label: "Labe", value: "8" },
    { label: "Fria", value: "9" },
    { label: "Boffa", value: "10" },
  ],

  163: [
    { label: "Bissau", value: "1" },
    { label: "Bafata", value: "2" },
    { label: "Gabú", value: "3" },
    { label: "Bissorã", value: "4" },
    { label: "Bubaque", value: "5" },
    { label: "Canchungo", value: "6" },
    { label: "Cacheu", value: "7" },
    { label: "Bolama", value: "8" },
    { label: "Farim", value: "9" },
    { label: "Mansoa", value: "10" },
  ],

  37: [
    { label: "Georgetown", value: "1" },
    { label: "Linden", value: "2" },
    { label: "New Amsterdam", value: "3" },
    { label: "Bartica", value: "4" },
    { label: "Skeldon", value: "5" },
    { label: "Rosignol", value: "6" },
    { label: "Mahaica Village", value: "7" },
    { label: "Parika", value: "8" },
    { label: "Vreed-en-Hoop", value: "9" },
    { label: "Ituni", value: "10" },
  ],
  18: [
    { label: "Port-au-Prince", value: "1" },
    { label: "Carrefour", value: "2" },
    { label: "Delmas", value: "3" },
    { label: "Pétion-Ville", value: "4" },
    { label: "Port-de-Paix", value: "5" },
    { label: "Jacmel", value: "6" },
    { label: "Cap-Haïtien", value: "7" },
    { label: "Léogâne", value: "8" },
    { label: "Les Cayes", value: "9" },
    { label: "Gonaïves", value: "10" },
  ],
  19: [
    { label: "Tegucigalpa", value: "1" },
    { label: "San Pedro Sula", value: "2" },
    { label: "Choloma", value: "3" },
    { label: "La Ceiba", value: "4" },
    { label: "El Progreso", value: "5" },
    { label: "Comayagua", value: "6" },
    { label: "Choluteca", value: "7" },
    { label: "Danlí", value: "8" },
    { label: "Siguatepeque", value: "9" },
    { label: "Juticalpa", value: "10" },
  ],
  105: [
    { label: "Hong Kong", value: "1" },
    { label: "Kowloon", value: "2" },
    { label: "Tsuen Wan", value: "3" },
    { label: "Yuen Long Kau Hui", value: "4" },
    { label: "Tuen Mun", value: "5" },
    { label: "Tai Po", value: "6" },
    { label: "Sha Tin", value: "7" },
    { label: "Tsim Sha Tsui", value: "8" },
    { label: "Wan Chai", value: "9" },
    { label: "Central", value: "10" },
  ],

  64: [
    { label: "Budapest", value: "1" },
    { label: "Debrecen", value: "2" },
    { label: "Miskolc", value: "3" },
    { label: "Szeged", value: "4" },
    { label: "Pécs", value: "5" },
    { label: "Győr", value: "6" },
    { label: "Nyíregyháza", value: "7" },
    { label: "Kecskemét", value: "8" },
    { label: "Székesfehérvár", value: "9" },
    { label: "Szombathely", value: "10" },
  ],

  65: [
    { label: "Reykjavik", value: "1" },
    { label: "Kopavogur", value: "2" },
    { label: "Hafnarfjordur", value: "3" },
    { label: "Akureyri", value: "4" },
    { label: "Reykjanesbær", value: "5" },
    { label: "Garðabær", value: "6" },
    { label: "Mosfellsbær", value: "7" },
    { label: "Árborg", value: "8" },
    { label: "Akranes", value: "9" },
    { label: "Fjarðabyggð", value: "10" },
  ],

  106: [
    { label: "Mumbai", value: "1" },
    { label: "Delhi", value: "2" },
    { label: "Bangalore", value: "3" },
    { label: "Hyderabad", value: "4" },
    { label: "Chennai", value: "5" },
    { label: "Kolkata", value: "6" },
    { label: "Ahmedabad", value: "7" },
    { label: "Pune", value: "8" },
    { label: "Surat", value: "9" },
    { label: "Jaipur", value: "10" },
  ],

  107: [
    { label: "Jakarta", value: "1" },
    { label: "Surabaya", value: "2" },
    { label: "Bandung", value: "3" },
    { label: "Medan", value: "4" },
    { label: "Semarang", value: "5" },
    { label: "Tangerang", value: "6" },
    { label: "Depok", value: "7" },
    { label: "Palembang", value: "8" },
    { label: "Makassar", value: "9" },
    { label: "Bekasi", value: "10" },
  ],
  108: [
    { label: "Tehran", value: "1" },
    { label: "Mashhad", value: "2" },
    { label: "Isfahan", value: "3" },
    { label: "Karaj", value: "4" },
    { label: "Tabriz", value: "5" },
    { label: "Shiraz", value: "6" },
    { label: "Qom", value: "7" },
    { label: "Ahvaz", value: "8" },
    { label: "Kermanshah", value: "9" },
    { label: "Urmia", value: "10" },
  ],

  109: [
    { label: "Baghdad", value: "1" },
    { label: "Basra", value: "2" },
    { label: "Sulaymaniyah", value: "3" },
    { label: "Erbil", value: "4" },
    { label: "Mosul", value: "5" },
    { label: "Kirkuk", value: "6" },
    { label: "Najaf", value: "7" },
    { label: "Karbala", value: "8" },
    { label: "Diyala", value: "9" },
    { label: "Dhi Qar", value: "10" },
  ],

  66: [
    { label: "Dublin", value: "1" },
    { label: "Cork", value: "2" },
    { label: "Limerick", value: "3" },
    { label: "Galway", value: "4" },
    { label: "Waterford", value: "5" },
    { label: "Drogheda", value: "6" },
    { label: "Dundalk", value: "7" },
    { label: "Bray", value: "8" },
    { label: "Navan", value: "9" },
    { label: "Ennis", value: "10" },
  ],

  67: [
    { label: "Douglas", value: "1" },
    { label: "Ramsey", value: "2" },
    { label: "Peel", value: "3" },
    { label: "Castletown", value: "4" },
    { label: "Port Erin", value: "5" },
    { label: "Laxey", value: "6" },
    { label: "Onchan", value: "7" },
    { label: "Ballivor", value: "8" },
    { label: "Ballasalla", value: "9" },
    { label: "Colby", value: "10" },
  ],

  110: [
    { label: "Jerusalem", value: "1" },
    { label: "Tel Aviv", value: "2" },
    { label: "Haifa", value: "3" },
    { label: "Rishon LeZion", value: "4" },
    { label: "Petah Tikva", value: "5" },
    { label: "Ashdod", value: "6" },
    { label: "Netanya", value: "7" },
    { label: "Beersheba", value: "8" },
    { label: "Holon", value: "9" },
    { label: "Bnei Brak", value: "10" },
  ],

  68: [
    { label: "Rome", value: "1" },
    { label: "Milan", value: "2" },
    { label: "Naples", value: "3" },
    { label: "Turin", value: "4" },
    { label: "Palermo", value: "5" },
    { label: "Genoa", value: "6" },
    { label: "Bologna", value: "7" },
    { label: "Florence", value: "8" },
    { label: "Venice", value: "9" },
    { label: "Verona", value: "10" },
  ],

  164: [
    { label: "Abidjan", value: "1" },
    { label: "Bouaké", value: "2" },
    { label: "Daloa", value: "3" },
    { label: "Yamoussoukro", value: "4" },
    { label: "San Pedro", value: "5" },
    { label: "Korhogo", value: "6" },
    { label: "Abobo", value: "7" },
    { label: "Man", value: "8" },
    { label: "Divo", value: "9" },
    { label: "Gagnoa", value: "10" },
  ],
  20: [
    { label: "Kingston", value: "1" },
    { label: "Montego Bay", value: "2" },
    { label: "Spanish Town", value: "3" },
    { label: "Portmore", value: "4" },
    { label: "Mandeville", value: "5" },
    { label: "Ocho Rios", value: "6" },
    { label: "May Pen", value: "7" },
    { label: "Savanna-la-Mar", value: "8" },
    { label: "Linstead", value: "9" },
    { label: "Half Way Tree", value: "10" },
  ],

  111: [
    { label: "Tokyo", value: "1" },
    { label: "Yokohama", value: "2" },
    { label: "Osaka", value: "3" },
    { label: "Nagoya", value: "4" },
    { label: "Sapporo", value: "5" },
    { label: "Fukuoka", value: "6" },
    { label: "Kobe", value: "7" },
    { label: "Kyoto", value: "8" },
    { label: "Saitama", value: "9" },
    { label: "Saitama", value: "10" },
  ],

  69: [
    { label: "Saint Helier", value: "1" },
    { label: "St. Clement", value: "2" },
    { label: "St. Lawrence", value: "3" },
    { label: "St. Saviour", value: "4" },
    { label: "Trinity", value: "5" },
    { label: "Grouville", value: "6" },
    { label: "St. Brélade", value: "7" },
    { label: "St. Mary", value: "8" },
    { label: "St. John", value: "9" },
    { label: "St. Peter", value: "10" },
  ],

  112: [
    { label: "Amman", value: "1" },
    { label: "Zarqa", value: "2" },
    { label: "Irbid", value: "3" },
    { label: "Aqaba", value: "4" },
    { label: "Salt", value: "5" },
    { label: "Ar Ramtha", value: "6" },
    { label: "Mafraq", value: "7" },
    { label: "Madaba", value: "8" },
    { label: "Ma'an", value: "9" },
    { label: "Karak", value: "10" },
  ],

  113: [
    { label: "Almaty", value: "1" },
    { label: "Nur-Sultan (Astana)", value: "2" },
    { label: "Shymkent", value: "3" },
    { label: "Karaganda", value: "4" },
    { label: "Aktobe", value: "5" },
    { label: "Taraz", value: "6" },
    { label: "Pavlodar", value: "7" },
    { label: "Ust-Kamenogorsk", value: "8" },
    { label: "Semey", value: "9" },
    { label: "Almaty Region", value: "10" },
  ],

  165: [
    { label: "Nairobi", value: "1" },
    { label: "Mombasa", value: "2" },
    { label: "Nakuru", value: "3" },
    { label: "Eldoret", value: "4" },
    { label: "Kisumu", value: "5" },
    { label: "Thika", value: "6" },
    { label: "Malindi", value: "7" },
    { label: "Kitale", value: "8" },
    { label: "Garissa", value: "9" },
    { label: "Kakamega", value: "10" },
  ],

  201: [
    { label: "Tarawa", value: "1" },
    { label: "Betio", value: "2" },
    { label: "Bairiki", value: "3" },
    { label: "Teinainano", value: "4" },
    { label: "Eita", value: "5" },
    { label: "Bonriki", value: "6" },
    { label: "Temaraia", value: "7" },
    { label: "Bikenibeu", value: "8" },
    { label: "Tabwakea", value: "9" },
    { label: "Rungata", value: "10" },
  ],

  70: [
    { label: "Pristina", value: "1" },
    { label: "Prizren", value: "2" },
    { label: "Gjakova", value: "3" },
    { label: "Peć", value: "4" },
    { label: "Mitrovica", value: "5" },
    { label: "Ferizaj", value: "6" },
    { label: "Glogovac", value: "7" },
    { label: "Podujevo", value: "8" },
    { label: "Uroševac", value: "9" },
    { label: "Vushtrri", value: "10" },
  ],

  114: [
    { label: "Kuwait City", value: "1" },
    { label: "Al Ahmadi", value: "2" },
    { label: "Hawalli", value: "3" },
    { label: "As Salimiyah", value: "4" },
    { label: "Sabah as Salim", value: "5" },
    { label: "Al Farwaniyah", value: "6" },
    { label: "Al Fahahil", value: "7" },
    { label: "Kuwait City", value: "8" },
    { label: "Ar Riqqah", value: "9" },
    { label: "Salwa", value: "10" },
  ],

  115: [
    { label: "Bishkek", value: "1" },
    { label: "Osh", value: "2" },
    { label: "Jalal-Abad", value: "3" },
    { label: "Karabalta", value: "4" },
    { label: "Kara-Balta", value: "5" },
    { label: "Tokmok", value: "6" },
    { label: "Kyzyl-Kiya", value: "7" },
    { label: "Isfana", value: "8" },
    { label: "Talas", value: "9" },
    { label: "Karakol", value: "10" },
  ],
  116: [
    { label: "Vientiane", value: "1" },
    { label: "Pakxe", value: "2" },
    { label: "Savannakhet", value: "3" },
    { label: "Luang Prabang", value: "4" },
    { label: "Thakhek", value: "5" },
    { label: "Muang Xay", value: "6" },
    { label: "Vang Vieng", value: "7" },
    { label: "Phonsavan", value: "8" },
    { label: "Xam Neua", value: "9" },
    { label: "Xayaboury", value: "10" },
  ],

  71: [
    { label: "Riga", value: "1" },
    { label: "Daugavpils", value: "2" },
    { label: "Liepāja", value: "3" },
    { label: "Jelgava", value: "4" },
    { label: "Jūrmala", value: "5" },
    { label: "Ventspils", value: "6" },
    { label: "Rēzekne", value: "7" },
    { label: "Valmiera", value: "8" },
    { label: "Ogre", value: "9" },
    { label: "Tukums", value: "10" },
  ],

  117: [
    { label: "Beirut", value: "1" },
    { label: "Tripoli", value: "2" },
    { label: "Sidon", value: "3" },
    { label: "Tyre", value: "4" },
    { label: "Jounieh", value: "5" },
    { label: "Zahle", value: "6" },
    { label: "Baabda", value: "7" },
    { label: "Byblos", value: "8" },
    { label: "Nabatieh", value: "9" },
    { label: "Anjar", value: "10" },
  ],

  166: [
    { label: "Maseru", value: "1" },
    { label: "Teyateyaneng", value: "2" },
    { label: "Mafeteng", value: "3" },
    { label: "Hlotse", value: "4" },
    { label: "Mohale's Hoek", value: "5" },
    { label: "Maputsoe", value: "6" },
    { label: "Qacha's Nek", value: "7" },
    { label: "Butha-Buthe", value: "8" },
    { label: "Mokhotlong", value: "9" },
    { label: "Thaba-Tseka", value: "10" },
  ],

  167: [
    { label: "Monrovia", value: "1" },
    { label: "Gbarnga", value: "2" },
    { label: "Kakata", value: "3" },
    { label: "Bensonville", value: "4" },
    { label: "Harper", value: "5" },
    { label: "Voinjama", value: "6" },
    { label: "Zwedru", value: "7" },
    { label: "New Yekepa", value: "8" },
    { label: "Ganta", value: "9" },
    { label: "Robertsport", value: "10" },
  ],

  168: [
    { label: "Tripoli", value: "1" },
    { label: "Benghazi", value: "2" },
    { label: "Misrata", value: "3" },
    { label: "Zawiya", value: "4" },
    { label: "Sirte", value: "5" },
    { label: "Al Khums", value: "6" },
    { label: "Zliten", value: "7" },
    { label: "Tobruk", value: "8" },
    { label: "Sabha", value: "9" },
    { label: "Al Marj", value: "10" },
  ],

  72: [
    { label: "Vaduz", value: "1" },
    { label: "Schellenberg", value: "2" },
    { label: "Triesenberg", value: "3" },
    { label: "Balzers", value: "4" },
    { label: "Eschen", value: "5" },
    { label: "Mauren", value: "6" },
    { label: "Triesen", value: "7" },
    { label: "Ruggell", value: "8" },
    { label: "Gamprin", value: "9" },
    { label: "Schaan", value: "10" },
  ],

  73: [
    { label: "Vilnius", value: "1" },
    { label: "Kaunas", value: "2" },
    { label: "Klaipėda", value: "3" },
    { label: "Šiauliai", value: "4" },
    { label: "Panevėžys", value: "5" },
    { label: "Alytus", value: "6" },
    { label: "Marijampolė", value: "7" },
    { label: "Mažeikiai", value: "8" },
    { label: "Jonava", value: "9" },
    { label: "Utena", value: "10" },
  ],

  74: [
    { label: "Luxembourg City", value: "1" },
    { label: "Esch-sur-Alzette", value: "2" },
    { label: "Differdange", value: "3" },
    { label: "Dudelange", value: "4" },
    { label: "Ettelbruck", value: "5" },
    { label: "Diekirch", value: "6" },
    { label: "Wiltz", value: "7" },
    { label: "Echternach", value: "8" },
    { label: "Rumelange", value: "9" },
    { label: "Grevenmacher", value: "10" },
  ],
  118: [
    { label: "Macau", value: "1" },
    { label: "Nossa Senhora do Carmo", value: "2" },
    { label: "Lapa", value: "3" },
    { label: "Santo António", value: "4" },
    { label: "São Lourenço", value: "5" },
    { label: "Sé", value: "6" },
    { label: "Taipa", value: "7" },
    { label: "Coloane", value: "8" },
    { label: "Cotai", value: "9" },
    { label: "Hac Sa Beach", value: "10" },
  ],

  75: [
    { label: "Skopje", value: "1" },
    { label: "Bitola", value: "2" },
    { label: "Kumanovo", value: "3" },
    { label: "Prilep", value: "4" },
    { label: "Tetovo", value: "5" },
    { label: "Veles", value: "6" },
    { label: "Ohrid", value: "7" },
    { label: "Gostivar", value: "8" },
    { label: "Strumica", value: "9" },
    { label: "Kochani", value: "10" },
  ],

  169: [
    { label: "Antananarivo", value: "1" },
    { label: "Toamasina", value: "2" },
    { label: "Antsirabe", value: "3" },
    { label: "Fianarantsoa", value: "4" },
    { label: "Mahajanga", value: "5" },
    { label: "Toliara", value: "6" },
    { label: "Antsiranana", value: "7" },
    { label: "Fenoarivo Atsinanana", value: "8" },
    { label: "Ambovombe", value: "9" },
    { label: "Ambanja", value: "10" },
  ],

  170: [
    { label: "Lilongwe", value: "1" },
    { label: "Blantyre", value: "2" },
    { label: "Mzuzu", value: "3" },
    { label: "Zomba", value: "4" },
    { label: "Kasungu", value: "5" },
    { label: "Mchinji", value: "6" },
    { label: "Balaka", value: "7" },
    { label: "Dedza", value: "8" },
    { label: "Nkhotakota", value: "9" },
    { label: "Monkey Bay", value: "10" },
  ],

  119: [
    { label: "Kuala Lumpur", value: "1" },
    { label: "George Town", value: "2" },
    { label: "Ipoh", value: "3" },
    { label: "Shah Alam", value: "4" },
    { label: "Petaling Jaya", value: "5" },
    { label: "Kuching", value: "6" },
    { label: "Kota Kinabalu", value: "7" },
    { label: "Sandakan", value: "8" },
    { label: "Seremban", value: "9" },
    { label: "Malacca City", value: "10" },
  ],

  120: [
    { label: "Malé", value: "1" },
    { label: "Hulhumalé", value: "2" },
    { label: "Kulhudhuffushi", value: "3" },
    { label: "Dhidhdhoo", value: "4" },
    { label: "Naifaru", value: "5" },
    { label: "Thinadhoo", value: "6" },
    { label: "Maafushi", value: "7" },
    { label: "Eydhafushi", value: "8" },
    { label: "Fuvahmulah", value: "9" },
    { label: "Guraidhoo", value: "10" },
  ],

  171: [
    { label: "Bamako", value: "1" },
    { label: "Sikasso", value: "2" },
    { label: "Mopti", value: "3" },
    { label: "Koutiala", value: "4" },
    { label: "Kayes", value: "5" },
    { label: "Ségou", value: "6" },
    { label: "Gao", value: "7" },
    { label: "Markala", value: "8" },
    { label: "Kati", value: "9" },
    { label: "Kolokani", value: "10" },
  ],

  76: [
    { label: "Valletta", value: "1" },
    { label: "Birkirkara", value: "2" },
    { label: "Mosta", value: "3" },
    { label: "Qormi", value: "4" },
    { label: "Zabbar", value: "5" },
    { label: "Sliema", value: "6" },
    { label: "Rabat", value: "7" },
    { label: "San Ġwann", value: "8" },
    { label: "Zejtun", value: "9" },
    { label: "Naxxar", value: "10" },
  ],

  202: [
    { label: "Majuro", value: "1" },
    { label: "Ebeye", value: "2" },
    { label: "Wotje", value: "3" },
    { label: "Jabor", value: "4" },
    { label: "Maloelap", value: "5" },
    { label: "Ailinglaplap", value: "6" },
    { label: "Wotho", value: "7" },
    { label: "Ujelang", value: "8" },
    { label: "Namu", value: "9" },
    { label: "Ebon", value: "10" },
  ],

  21: [
    { label: "Fort-de-France", value: "1" },
    { label: "Le Lamentin", value: "2" },
    { label: "Sainte-Marie", value: "3" },
    { label: "Le Robert", value: "4" },
    { label: "Sainte-Luce", value: "5" },
    { label: "Le François", value: "6" },
    { label: "Schœlcher", value: "7" },
    { label: "Ducos", value: "8" },
    { label: "Saint-Joseph", value: "9" },
    { label: "Le Gosier", value: "10" },
  ],
  172: [
    { label: "Nouakchott", value: "1" },
    { label: "Nouadhibou", value: "2" },
    { label: "Rosso", value: "3" },
    { label: "Zouérat", value: "4" },
    { label: "Atar", value: "5" },
    { label: "Kaédi", value: "6" },
    { label: "Aleg", value: "7" },
    { label: "Tidjikja", value: "8" },
    { label: "Selibaby", value: "9" },
    { label: "Kiffa", value: "10" },
  ],

  173: [
    { label: "Port Louis", value: "1" },
    { label: "Beau Bassin-Rose Hill", value: "2" },
    { label: "Vacoas-Phoenix", value: "3" },
    { label: "Curepipe", value: "4" },
    { label: "Quatre Bornes", value: "5" },
    { label: "Triolet", value: "6" },
    { label: "Goodlands", value: "7" },
    { label: "Centre de Flacq", value: "8" },
    { label: "Bel Air Rivière Sèche", value: "9" },
    { label: "Mahebourg", value: "10" },
  ],

  22: [
    { label: "Mexico City", value: "1" },
    { label: "Ecatepec", value: "2" },
    { label: "Guadalajara", value: "3" },
    { label: "Puebla", value: "4" },
    { label: "Tijuana", value: "5" },
    { label: "León", value: "6" },
    { label: "Juárez", value: "7" },
    { label: "Zapopan", value: "8" },
    { label: "Monterrey", value: "9" },
    { label: "Nezahualcóyotl", value: "10" },
  ],

  203: [
    { label: "Palikir", value: "1" },
    { label: "Weno", value: "2" },
    { label: "Kolonia", value: "3" },
    { label: "Tonoas", value: "4" },
    { label: "Kitti", value: "5" },
    { label: "Kapingamarangi", value: "6" },
    { label: "Nan Madol", value: "7" },
    { label: "Sokehs", value: "8" },
    { label: "Malem", value: "9" },
    { label: "U", value: "10" },
  ],

  77: [
    { label: "Chisinau", value: "1" },
    { label: "Tiraspol", value: "2" },
    { label: "Bălți", value: "3" },
    { label: "Bender", value: "4" },
    { label: "Rîbnița", value: "5" },
    { label: "Cahul", value: "6" },
    { label: "Ungheni", value: "7" },
    { label: "Soroca", value: "8" },
    { label: "Orhei", value: "9" },
    { label: "Dubăsari", value: "10" },
  ],

  78: [
    { label: "Monaco", value: "1" },
    { label: "Monte-Carlo", value: "2" },
    { label: "La Condamine", value: "3" },
    { label: "Fontvieille", value: "4" },
    { label: "Les Moneghetti", value: "5" },
    { label: "Larvotto", value: "6" },
    { label: "Saint-Roman", value: "7" },
    { label: "Moulins", value: "8" },
    { label: "Jardin Exotique", value: "9" },
    { label: "La Colle", value: "10" },
  ],

  121: [
    { label: "Ulaanbaatar", value: "1" },
    { label: "Erdenet", value: "2" },
    { label: "Darkhan", value: "3" },
    { label: "Choibalsan", value: "4" },
    { label: "Khovd", value: "5" },
    { label: "Olgii", value: "6" },
    { label: "Uvs", value: "7" },
    { label: "Bulgan", value: "8" },
    { label: "Baruun-Urt", value: "9" },
    { label: "Mörön", value: "10" },
  ],

  79: [
    { label: "Podgorica", value: "1" },
    { label: "Nikšić", value: "2" },
    { label: "Pljevlja", value: "3" },
    { label: "Herceg Novi", value: "4" },
    { label: "Bar", value: "5" },
    { label: "Budva", value: "6" },
    { label: "Kotor", value: "7" },
    { label: "Berane", value: "8" },
    { label: "Cetinje", value: "9" },
    { label: "Rožaje", value: "10" },
  ],

  23: [
    { label: "Plymouth", value: "1" },
    { label: "Brades", value: "2" },
    { label: "Lookout", value: "3" },
    { label: "St. John's", value: "4" },
    { label: "Salem", value: "5" },
    { label: "Zanesville", value: "6" },
    { label: "Saint Peter's", value: "7" },
    { label: "Fogarty", value: "8" },
    { label: "Carr's Bay", value: "9" },
    { label: "Kinsale", value: "10" },
  ],

  174: [
    { label: "Casablanca", value: "1" },
    { label: "Rabat", value: "2" },
    { label: "Fes", value: "3" },
    { label: "Sale", value: "4" },
    { label: "Marrakech", value: "5" },
    { label: "Agadir", value: "6" },
    { label: "Tangier", value: "7" },
    { label: "Meknes", value: "8" },
    { label: "Oujda", value: "9" },
    { label: "Kenitra", value: "10" },
  ],

  175: [
    { label: "Maputo", value: "1" },
    { label: "Matola", value: "2" },
    { label: "Beira", value: "3" },
    { label: "Nampula", value: "4" },
    { label: "Chimoio", value: "5" },
    { label: "Cidade de Nacala", value: "6" },
    { label: "Quelimane", value: "7" },
    { label: "Tete", value: "8" },
    { label: "Xai-Xai", value: "9" },
    { label: "Maxixe", value: "10" },
  ],

  122: [
    { label: "Yangon", value: "1" },
    { label: "Mandalay", value: "2" },
    { label: "Naypyidaw", value: "3" },
    { label: "Mawlamyine", value: "4" },
    { label: "Bago", value: "5" },
    { label: "Pathein", value: "6" },
    { label: "Monywa", value: "7" },
    { label: "Meiktila", value: "8" },
    { label: "Sittwe", value: "9" },
    { label: "Taunggyi", value: "10" },
  ],

  176: [
    { label: "Windhoek", value: "1" },
    { label: "Rundu", value: "2" },
    { label: "Walvis Bay", value: "3" },
    { label: "Oshakati", value: "4" },
    { label: "Swakopmund", value: "5" },
    { label: "Katima Mulilo", value: "6" },
    { label: "Grootfontein", value: "7" },
    { label: "Rehoboth", value: "8" },
    { label: "Otjiwarongo", value: "9" },
    { label: "Okahandja", value: "10" },
  ],

  204: [
    { label: "Yaren", value: "1" },
    { label: "Denigomodu", value: "2" },
    { label: "Anabar", value: "3" },
    { label: "Uaboe", value: "4" },
    { label: "Anibare", value: "5" },
    { label: "Baiti", value: "6" },
    { label: "Boe", value: "7" },
    { label: "Buada", value: "8" },
    { label: "Denigoman", value: "9" },
    { label: "Ewa", value: "10" },
  ],

  123: [
    { label: "Kathmandu", value: "1" },
    { label: "Pokhara", value: "2" },
    { label: "Patan", value: "3" },
    { label: "Biratnagar", value: "4" },
    { label: "Dharan", value: "5" },
    { label: "Bharatpur", value: "6" },
    { label: "Birgunj", value: "7" },
    { label: "Hetauda", value: "8" },
    { label: "Butwal", value: "9" },
    { label: "Dhangadhi", value: "10" },
  ],

  80: [
    { label: "Amsterdam", value: "1" },
    { label: "Rotterdam", value: "2" },
    { label: "The Hague", value: "3" },
    { label: "Utrecht", value: "4" },
    { label: "Eindhoven", value: "5" },
    { label: "Tilburg", value: "6" },
    { label: "Groningen", value: "7" },
    { label: "Almere", value: "8" },
    { label: "Breda", value: "9" },
    { label: "Nijmegen", value: "10" },
  ],

  205: [
    { label: "Nouméa", value: "1" },
    { label: "Dumbéa", value: "2" },
    { label: "Mont-Dore", value: "3" },
    { label: "Païta", value: "4" },
    { label: "Wé", value: "5" },
    { label: "Tadine", value: "6" },
    { label: "Poindimié", value: "7" },
    { label: "Koné", value: "8" },
    { label: "Voh", value: "9" },
    { label: "Koumac", value: "10" },
  ],

  197: [
    { label: "Auckland", value: "1" },
    { label: "Wellington", value: "2" },
    { label: "Christchurch", value: "3" },
    { label: "Hamilton", value: "4" },
    { label: "Tauranga", value: "5" },
    { label: "Dunedin", value: "6" },
    { label: "Palmerston North", value: "7" },
    { label: "Napier-Hastings", value: "8" },
    { label: "Auckland", value: "9" },
    { label: "Rotorua", value: "10" },
  ],

  24: [
    { label: "Managua", value: "1" },
    { label: "León", value: "2" },
    { label: "Masaya", value: "3" },
    { label: "Matagalpa", value: "4" },
    { label: "Chinandega", value: "5" },
    { label: "Estelí", value: "6" },
    { label: "Granada", value: "7" },
    { label: "Ciudad Sandino", value: "8" },
    { label: "Juigalpa", value: "9" },
    { label: "El Viejo", value: "10" },
  ],

  177: [
    { label: "Niamey", value: "1" },
    { label: "Zinder", value: "2" },
    { label: "Maradi", value: "3" },
    { label: "Agadez", value: "4" },
    { label: "Alaghsas", value: "5" },
    { label: "Arlit", value: "6" },
    { label: "Birni Nkonni", value: "7" },
    { label: "Dosso", value: "8" },
    { label: "Gaya", value: "9" },
    { label: "Tessaoua", value: "10" },
  ],
  178: [
    { label: "Lagos", value: "1" },
    { label: "Kano", value: "2" },
    { label: "Ibadan", value: "3" },
    { label: "Kaduna", value: "4" },
    { label: "Port Harcourt", value: "5" },
    { label: "Benin City", value: "6" },
    { label: "Maiduguri", value: "7" },
    { label: "Zaria", value: "8" },
    { label: "Aba", value: "9" },
    { label: "Jos", value: "10" },
  ],

  124: [
    { label: "Pyongyang", value: "1" },
    { label: "Hamhung", value: "2" },
    { label: "Chongjin", value: "3" },
    { label: "Nampo", value: "4" },
    { label: "Wonsan", value: "5" },
    { label: "Sinuiju", value: "6" },
    { label: "Haeju", value: "7" },
    { label: "Kaesong", value: "8" },
    { label: "Sariwon", value: "9" },
    { label: "Hyesan", value: "10" },
  ],

  411: [
    { label: "Nicosia", value: "1" },
    { label: "Kyrenia", value: "2" },
    { label: "Famagusta", value: "3" },
    { label: "Morphou", value: "4" },
    { label: "Rizokarpaso", value: "5" },
    { label: "Kokkina", value: "6" },
    { label: "Lefka", value: "7" },
    { label: "Salamis", value: "8" },
    { label: "Paphos", value: "9" },
    { label: "Limassol", value: "10" },
  ],

  414: [
    { label: "Saipan", value: "1" },
    { label: "San Jose", value: "2" },
    { label: "Dandan", value: "3" },
    { label: "Garapan", value: "4" },
    { label: "Kagman", value: "5" },
    { label: "Chalan Kanoa", value: "6" },
    { label: "San Roque", value: "7" },
    { label: "Capital Hill", value: "8" },
    { label: "Tanapag", value: "9" },
    { label: "Oleai", value: "10" },
  ],

  81: [
    { label: "Oslo", value: "1" },
    { label: "Bergen", value: "2" },
    { label: "Stavanger", value: "3" },
    { label: "Trondheim", value: "4" },
    { label: "Drammen", value: "5" },
    { label: "Fredrikstad", value: "6" },
    { label: "Kristiansand", value: "7" },
    { label: "Sandnes", value: "8" },
    { label: "Tromsø", value: "9" },
    { label: "Sarpsborg", value: "10" },
  ],

  125: [
    { label: "Muscat", value: "1" },
    { label: "Seeb", value: "2" },
    { label: "Salalah", value: "3" },
    { label: "Bawshar", value: "4" },
    { label: "Sohar", value: "5" },
    { label: "As Suwayq", value: "6" },
    { label: "Ibri", value: "7" },
    { label: "Saham", value: "8" },
    { label: "Rustaq", value: "9" },
    { label: "Sur", value: "10" },
  ],

  126: [
    { label: "Karachi", value: "1" },
    { label: "Lahore", value: "2" },
    { label: "Faisalabad", value: "3" },
    { label: "Rawalpindi", value: "4" },
    { label: "Multan", value: "5" },
    { label: "Gujranwala", value: "6" },
    { label: "Islamabad", value: "7" },
    { label: "Peshawar", value: "8" },
    { label: "Quetta", value: "9" },
    { label: "Sialkot", value: "10" },
  ],

  228: [
    { label: "Jerusalem", value: "1" },
    { label: "Gaza City", value: "2" },
    { label: "Hebron", value: "3" },
    { label: "Nablus", value: "4" },
    { label: "Rafah", value: "5" },
    { label: "Jenin", value: "6" },
    { label: "Ramallah", value: "7" },
    { label: "Tulkarm", value: "8" },
    { label: "Qalqilya", value: "9" },
    { label: "Beit Lahia", value: "10" },
  ],

  25: [
    { label: "Panama City", value: "1" },
    { label: "San Miguelito", value: "2" },
    { label: "Tocumen", value: "3" },
    { label: "David", value: "4" },
    { label: "Arraiján", value: "5" },
    { label: "Colón", value: "6" },
    { label: "Las Cumbres", value: "7" },
    { label: "La Chorrera", value: "8" },
    { label: "Pacora", value: "9" },
    { label: "Chitré", value: "10" },
  ],

  206: [
    { label: "Port Moresby", value: "1" },
    { label: "Lae", value: "2" },
    { label: "Mount Hagen", value: "3" },
    { label: "Madang", value: "4" },
    { label: "Wewak", value: "5" },
    { label: "Goroka", value: "6" },
    { label: "Kimbe", value: "7" },
    { label: "Arawa", value: "8" },
    { label: "Popondetta", value: "9" },
    { label: "Mendi", value: "10" },
  ],
  38: [
    { label: "Asunción", value: "1" },
    { label: "San Lorenzo", value: "2" },
    { label: "Capiatá", value: "3" },
    { label: "Lambaré", value: "4" },
    { label: "Fernando de la Mora", value: "5" },
    { label: "Luque", value: "6" },
    { label: "Limpio", value: "7" },
    { label: "Ñemby", value: "8" },
    { label: "Encarnación", value: "9" },
    { label: "Ciudad del Este", value: "10" },
  ],

  39: [
    { label: "Lima", value: "1" },
    { label: "Arequipa", value: "2" },
    { label: "Callao", value: "3" },
    { label: "Trujillo", value: "4" },
    { label: "Chiclayo", value: "5" },
    { label: "Iquitos", value: "6" },
    { label: "Piura", value: "7" },
    { label: "Cusco", value: "8" },
    { label: "Chimbote", value: "9" },
    { label: "Huancayo", value: "10" },
  ],

  127: [
    { label: "Manila", value: "1" },
    { label: "Quezon City", value: "2" },
    { label: "Davao City", value: "3" },
    { label: "Cebu City", value: "4" },
    { label: "Makati", value: "5" },
    { label: "Taguig", value: "6" },
    { label: "Pasig", value: "7" },
    { label: "Antipolo", value: "8" },
    { label: "Cagayan de Oro", value: "9" },
    { label: "Parañaque", value: "10" },
  ],

  82: [
    { label: "Warsaw", value: "1" },
    { label: "Kraków", value: "2" },
    { label: "Łódź", value: "3" },
    { label: "Wrocław", value: "4" },
    { label: "Poznań", value: "5" },
    { label: "Gdańsk", value: "6" },
    { label: "Szczecin", value: "7" },
    { label: "Bydgoszcz", value: "8" },
    { label: "Lublin", value: "9" },
    { label: "Katowice", value: "10" },
  ],

  83: [
    { label: "Lisbon", value: "1" },
    { label: "Porto", value: "2" },
    { label: "Amadora", value: "3" },
    { label: "Braga", value: "4" },
    { label: "Setúbal", value: "5" },
    { label: "Coimbra", value: "6" },
    { label: "Queluz", value: "7" },
    { label: "Funchal", value: "8" },
    { label: "Cacém", value: "9" },
    { label: "Vila Nova de Gaia", value: "10" },
  ],

  26: [
    { label: "San Juan", value: "1" },
    { label: "Bayamón", value: "2" },
    { label: "Carolina", value: "3" },
    { label: "Ponce", value: "4" },
    { label: "Caguas", value: "5" },
    { label: "Guaynabo", value: "6" },
    { label: "Mayagüez", value: "7" },
    { label: "Trujillo Alto", value: "8" },
    { label: "Arecibo", value: "9" },
    { label: "Fajardo", value: "10" },
  ],

  128: [
    { label: "Doha", value: "1" },
    { label: "Al Rayyan", value: "2" },
    { label: "Umm Salal", value: "3" },
    { label: "Al Khor", value: "4" },
    { label: "Al Wakrah", value: "5" },
    { label: "Al Ahmadi", value: "6" },
    { label: "Lusail", value: "7" },
    { label: "Mesaieed", value: "8" },
    { label: "Al Daayen", value: "9" },
    { label: "Madinat Al Shamal", value: "10" },
  ],

  152: [
    { label: "Brazzaville", value: "1" },
    { label: "Pointe-Noire", value: "2" },
    { label: "Dolisie", value: "3" },
    { label: "Nkayi", value: "4" },
    { label: "Loandjili", value: "5" },
    { label: "Sibiti", value: "6" },
    { label: "Madingou", value: "7" },
    { label: "Owando", value: "8" },
    { label: "Gamboma", value: "9" },
    { label: "Impfondo", value: "10" },
  ],

  179: [
    { label: "Saint-Denis", value: "1" },
    { label: "Saint-Paul", value: "2" },
    { label: "Saint-Pierre", value: "3" },
    { label: "Le Tampon", value: "4" },
    { label: "Saint-André", value: "5" },
    { label: "Saint-Louis", value: "6" },
    { label: "Le Port", value: "7" },
    { label: "Saint-Benoît", value: "8" },
    { label: "Saint-Joseph", value: "9" },
    { label: "Sainte-Marie", value: "10" },
  ],

  84: [
    { label: "Bucharest", value: "1" },
    { label: "Cluj-Napoca", value: "2" },
    { label: "Timișoara", value: "3" },
    { label: "Iași", value: "4" },
    { label: "Craiova", value: "5" },
    { label: "Brașov", value: "6" },
    { label: "Galați", value: "7" },
    { label: "Ploiești", value: "8" },
    { label: "Oradea", value: "9" },
    { label: "Brăila", value: "10" },
  ],
  85: [
    { label: "Moscow", value: "1" },
    { label: "Saint Petersburg", value: "2" },
    { label: "Novosibirsk", value: "3" },
    { label: "Yekaterinburg", value: "4" },
    { label: "Kazan", value: "5" },
    { label: "Nizhny Novgorod", value: "6" },
    { label: "Chelyabinsk", value: "7" },
    { label: "Omsk", value: "8" },
    { label: "Samara", value: "9" },
    { label: "Rostov-on-Don", value: "10" },
  ],

  180: [
    { label: "Kigali", value: "1" },
    { label: "Butare", value: "2" },
    { label: "Gitarama", value: "3" },
    { label: "Ruhengeri", value: "4" },
    { label: "Gisenyi", value: "5" },
    { label: "Byumba", value: "6" },
    { label: "Cyangugu", value: "7" },
    { label: "Kibuye", value: "8" },
    { label: "Nyagatare", value: "9" },
    { label: "Nyanza", value: "10" },
  ],

  400: [
    { label: "Gustavia", value: "1" },
    { label: "Lorient", value: "2" },
    { label: "Corossol", value: "3" },
    { label: "Anse des Cayes", value: "4" },
    { label: "Flamands", value: "5" },
    { label: "Marigot", value: "6" },
    { label: "Grand Cul-de-Sac", value: "7" },
    { label: "Vitet", value: "8" },
    { label: "Public", value: "9" },
    { label: "Gouverneur", value: "10" },
  ],

  413: [
    { label: "Basseterre", value: "1" },
    { label: "Charlestown", value: "2" },
    { label: "Dieppe Bay Town", value: "3" },
    { label: "Half Way Tree", value: "4" },
    { label: "Cayon", value: "5" },
    { label: "Sandy Point Town", value: "6" },
    { label: "Monkey Hill", value: "7" },
    { label: "Gingerland", value: "8" },
    { label: "New Castle", value: "9" },
    { label: "Old Road Town", value: "10" },
  ],

  401: [
    { label: "Castries", value: "1" },
    { label: "Vieux Fort", value: "2" },
    { label: "Micoud", value: "3" },
    { label: "Soufrière", value: "4" },
    { label: "Dennery", value: "5" },
    { label: "Gros Islet", value: "6" },
    { label: "Laborie", value: "7" },
    { label: "Anse La Raye", value: "8" },
    { label: "Canaries", value: "9" },
    { label: "Anse Des Sables", value: "10" },
  ],

  207: [
    { label: "Apia", value: "1" },
    { label: "Vaitele", value: "2" },
    { label: "Siusega", value: "3" },
    { label: "Malie", value: "4" },
    { label: "Faleula", value: "5" },
    { label: "Fasito'o Uta", value: "6" },
    { label: "Satapuala", value: "7" },
    { label: "Afenga", value: "8" },
    { label: "Leulumoega", value: "9" },
    { label: "Lufilufi", value: "10" },
  ],

  86: [
    { label: "Moscow", value: "1" },
    { label: "Saint Petersburg", value: "2" },
    { label: "Novosibirsk", value: "3" },
    { label: "Yekaterinburg", value: "4" },
    { label: "Kazan", value: "5" },
    { label: "Nizhny Novgorod", value: "6" },
    { label: "Chelyabinsk", value: "7" },
    { label: "Omsk", value: "8" },
    { label: "Samara", value: "9" },
    { label: "Rostov-on-Don", value: "10" },
  ],

  181: [
    { label: "São Tomé", value: "1" },
    { label: "Neves", value: "2" },
    { label: "Guadalupe", value: "3" },
    { label: "Santana", value: "4" },
    { label: "São João dos Angolares", value: "5" },
    { label: "Santo António", value: "6" },
    { label: "Trindade", value: "7" },
    { label: "São Sebastião", value: "8" },
    { label: "Porto Alegre", value: "9" },
    { label: "Baucau", value: "10" },
  ],

  129: [
    { label: "Riyadh", value: "1" },
    { label: "Jeddah", value: "2" },
    { label: "Mecca", value: "3" },
    { label: "Medina", value: "4" },
    { label: "Dammam", value: "5" },
    { label: "Khobar", value: "6" },
    { label: "Jubail", value: "7" },
    { label: "Tabuk", value: "8" },
    { label: "Abha", value: "9" },
    { label: "Buraydah", value: "10" },
  ],

  182: [
    { label: "Dakar", value: "1" },
    { label: "Grand Dakar", value: "2" },
    { label: "Thiès", value: "3" },
    { label: "Saint-Louis", value: "4" },
    { label: "Kaolack", value: "5" },
    { label: "Ziguinchor", value: "6" },
    { label: "Rufisque", value: "7" },
    { label: "Fatick", value: "8" },
    { label: "Kolda", value: "9" },
    { label: "M'Bour", value: "10" },
  ],
  87: [
    { label: "Belgrade", value: "1" },
    { label: "Novi Sad", value: "2" },
    { label: "Niš", value: "3" },
    { label: "Kragujevac", value: "4" },
    { label: "Subotica", value: "5" },
    { label: "Čačak", value: "6" },
    { label: "Zrenjanin", value: "7" },
    { label: "Pancevo", value: "8" },
    { label: "Novi Pazar", value: "9" },
    { label: "Kraljevo", value: "10" },
  ],

  183: [
    { label: "Victoria", value: "1" },
    { label: "Anse Royale", value: "2" },
    { label: "Beau Vallon", value: "3" },
    { label: "Takamaka", value: "4" },
    { label: "Port Glaud", value: "5" },
    { label: "Anse La Mouche", value: "6" },
    { label: "Baie Lazare", value: "7" },
    { label: "Grand Anse Mahe", value: "8" },
    { label: "Glacis", value: "9" },
    { label: "Bel Ombre", value: "10" },
  ],

  184: [
    { label: "Freetown", value: "1" },
    { label: "Kenema", value: "2" },
    { label: "Bo", value: "3" },
    { label: "Koidu", value: "4" },
    { label: "Makeni", value: "5" },
    { label: "Lunsar", value: "6" },
    { label: "Port Loko", value: "7" },
    { label: "Kabala", value: "8" },
    { label: "Magburaka", value: "9" },
    { label: "Kailahun", value: "10" },
  ],

  130: [
    { label: "Singapore", value: "1" },
    { label: "Woodlands", value: "2" },
    { label: "Jurong East", value: "3" },
    { label: "Tampines", value: "4" },
    { label: "Ang Mo Kio", value: "5" },
    { label: "Bedok", value: "6" },
    { label: "Sengkang", value: "7" },
    { label: "Hougang", value: "8" },
    { label: "Yishun", value: "9" },
    { label: "Choa Chu Kang", value: "10" },
  ],

  88: [
    { label: "Bratislava", value: "1" },
    { label: "Košice", value: "2" },
    { label: "Prešov", value: "3" },
    { label: "Nitra", value: "4" },
    { label: "Žilina", value: "5" },
    { label: "Banská Bystrica", value: "6" },
    { label: "Trnava", value: "7" },
    { label: "Martin", value: "8" },
    { label: "Trenčín", value: "9" },
    { label: "Poprad", value: "10" },
  ],

  89: [
    { label: "Ljubljana", value: "1" },
    { label: "Maribor", value: "2" },
    { label: "Celje", value: "3" },
    { label: "Kranj", value: "4" },
    { label: "Velenje", value: "5" },
    { label: "Koper", value: "6" },
    { label: "Novo Mesto", value: "7" },
    { label: "Ptuj", value: "8" },
    { label: "Trbovlje", value: "9" },
    { label: "Kamnik", value: "10" },
  ],

  208: [
    { label: "Honiara", value: "1" },
    { label: "Gizo", value: "2" },
    { label: "Auki", value: "3" },
    { label: "Malu'u", value: "4" },
    { label: "Kirakira", value: "5" },
    { label: "Tulagi", value: "6" },
    { label: "Buala", value: "7" },
    { label: "Lata", value: "8" },
    { label: "Taro", value: "9" },
    { label: "Munda", value: "10" },
  ],

  185: [
    { label: "Mogadishu", value: "1" },
    { label: "Hargeisa", value: "2" },
    { label: "Berbera", value: "3" },
    { label: "Kismayo", value: "4" },
    { label: "Jamaame", value: "5" },
    { label: "Baidoa", value: "6" },
    { label: "Bosaso", value: "7" },
    { label: "Garowe", value: "8" },
    { label: "Jawhar", value: "9" },
    { label: "Afgooye", value: "10" },
  ],

  186: [
    { label: "Johannesburg", value: "1" },
    { label: "Cape Town", value: "2" },
    { label: "Durban", value: "3" },
    { label: "Pretoria", value: "4" },
    { label: "Port Elizabeth", value: "5" },
    { label: "Bloemfontein", value: "6" },
    { label: "East London", value: "7" },
    { label: "Vereeniging", value: "8" },
    { label: "Boksburg", value: "9" },
    { label: "Welkom", value: "10" },
  ],

  131: [
    { label: "Seoul", value: "1" },
    { label: "Busan", value: "2" },
    { label: "Incheon", value: "3" },
    { label: "Daegu", value: "4" },
    { label: "Daejeon", value: "5" },
    { label: "Gwangju", value: "6" },
    { label: "Suwon", value: "7" },
    { label: "Ulsan", value: "8" },
    { label: "Changwon", value: "9" },
    { label: "Goyang", value: "10" },
  ],
  403: [
    { label: "Juba", value: "1" },
    { label: "Wau", value: "2" },
    { label: "Malakal", value: "3" },
    { label: "Bor", value: "4" },
    { label: "Yei", value: "5" },
    { label: "Aweil", value: "6" },
    { label: "Rumbek", value: "7" },
    { label: "Bentiu", value: "8" },
    { label: "Torit", value: "9" },
    { label: "Yambio", value: "10" }
  ],
  90: [
    { label: "Madrid", value: "1" },
    { label: "Barcelona", value: "2" },
    { label: "Valencia", value: "3" },
    { label: "Seville", value: "4" },
    { label: "Zaragoza", value: "5" },
    { label: "Málaga", value: "6" },
    { label: "Murcia", value: "7" },
    { label: "Palma", value: "8" },
    { label: "Las Palmas de Gran Canaria", value: "9" },
    { label: "Bilbao", value: "10" }
  ],
  132: [
    { label: "Colombo", value: "1" },
    { label: "Kandy", value: "2" },
    { label: "Galle", value: "3" },
    { label: "Jaffna", value: "4" },
    { label: "Negombo", value: "5" },
    { label: "Trincomalee", value: "6" },
    { label: "Kalmunai", value: "7" },
    { label: "Matara", value: "8" },
    { label: "Anuradhapura", value: "9" },
    { label: "Batticaloa", value: "10" }
  ],
  187: [
    { label: "Khartoum", value: "1" },
    { label: "Omdurman", value: "2" },
    { label: "Port Sudan", value: "3" },
    { label: "Kassala", value: "4" },
    { label: "Al-Ubayyid", value: "5" },
    { label: "Nyala", value: "6" },
    { label: "Wad Madani", value: "7" },
    { label: "El Fasher", value: "8" },
    { label: "Ad-Damazin", value: "9" },
    { label: "Geneina", value: "10" }
  ],
  40: [
    { label: "Paramaribo", value: "1" },
    { label: "Lelydorp", value: "2" },
    { label: "Nieuw Nickerie", value: "3" },
    { label: "Moengo", value: "4" },
    { label: "Nieuw Amsterdam", value: "5" },
    { label: "Mariënburg", value: "6" },
    { label: "Wageningen", value: "7" },
    { label: "Albina", value: "8" },
    { label: "Groningen", value: "9" },
    { label: "Brownsweg", value: "10" }
  ],
 188: [
    { label: "Mbabane", value: "1" },
    { label: "Manzini", value: "2" },
    { label: "Big Bend", value: "3" },
    { label: "Malkerns", value: "4" },
    { label: "Nhlangano", value: "5" },
    { label: "Mhlume", value: "6" },
    { label: "Siteki", value: "7" },
    { label: "Piggs Peak", value: "8" },
    { label: "Lobamba", value: "9" },
    { label: "Hluti", value: "10" }
  ],
  91: [
    { label: "Stockholm", value: "1" },
    { label: "Gothenburg", value: "2" },
    { label: "Malmö", value: "3" },
    { label: "Uppsala", value: "4" },
    { label: "Linköping", value: "5" },
    { label: "Västerås", value: "6" },
    { label: "Örebro", value: "7" },
    { label: "Helsingborg", value: "8" },
    { label: "Jönköping", value: "9" },
    { label: "Norrköping", value: "10" }
  ],
  92: [
    { label: "Zurich", value: "1" },
    { label: "Geneva", value: "2" },
    { label: "Basel", value: "3" },
    { label: "Bern", value: "4" },
    { label: "Lausanne", value: "5" },
    { label: "Lucerne", value: "6" },
    { label: "St. Gallen", value: "7" },
    { label: "Winterthur", value: "8" },
    { label: "Lugano", value: "9" },
    { label: "Bienna", value: "10" }
  ],
  133: [
    { label: "Damascus", value: "1" },
    { label: "Aleppo", value: "2" },
    { label: "Homs", value: "3" },
    { label: "Hama", value: "4" },
    { label: "Latakia", value: "5" },
    { label: "Palmyra", value: "6" },
    { label: "Deir ez-Zor", value: "7" },
    { label: "Raqqa", value: "8" },
    { label: "Idlib", value: "9" },
    { label: "Daraa", value: "10" }
  ],
  134: [
    { label: "Taipei", value: "1" },
    { label: "New Taipei City", value: "2" },
    { label: "Taichung", value: "3" },
    { label: "Tainan", value: "4" },
    { label: "Kaohsiung", value: "5" },
    { label: "Keelung", value: "6" },
    { label: "Hsinchu", value: "7" },
    { label: "Taoyuan", value: "8" },
    { label: "Chiayi", value: "9" },
    { label: "Hualien City", value: "10" }
  ],

  135: [
    { label: "Dushanbe", value: "1" },
    { label: "Khujand", value: "2" },
    { label: "Kulob", value: "3" },
    { label: "Qurghonteppa", value: "4" },
    { label: "Istaravshan", value: "5" },
    { label: "Vahdat", value: "6" },
    { label: "Tursunzoda", value: "7" },
    { label: "Isfara", value: "8" },
    { label: "Kofarnihon", value: "9" },
    { label: "Konibodom", value: "10" }
  ],
  189: [
    { label: "Dodoma", value: "1" },
    { label: "Dar es Salaam", value: "2" },
    { label: "Mwanza", value: "3" },
    { label: "Arusha", value: "4" },
    { label: "Mbeya", value: "5" },
    { label: "Morogoro", value: "6" },
    { label: "Tanga", value: "7" },
    { label: "Dodoma", value: "8" },
    { label: "Kigoma", value: "9" },
    { label: "Moshi", value: "10" }
  ],
  136: [
    { label: "Bangkok", value: "1" },
    { label: "Nonthaburi", value: "2" },
    { label: "Nakhon Ratchasima", value: "3" },
    { label: "Chiang Mai", value: "4" },
    { label: "Hat Yai", value: "5" },
    { label: "Udon Thani", value: "6" },
    { label: "Pak Kret", value: "7" },
    { label: "Nakhon Sawan", value: "8" },
    { label: "Ubon Ratchathani", value: "9" },
    { label: "Khon Kaen", value: "10" }
  ],
  190: [
    { label: "Lome", value: "1" },
    { label: "Sokodé", value: "2" },
    { label: "Kara", value: "3" },
    { label: "Palimé", value: "4" },
    { label: "Atakpamé", value: "5" },
    { label: "Bassar", value: "6" },
    { label: "Tsévié", value: "7" },
    { label: "Aného", value: "8" },
    { label: "Sansanné-Mango", value: "9" },
    { label: "Dapaong", value: "10" }
  ],
  209: [
    { label: "Nuku'alofa", value: "1" },
    { label: "Neiafu", value: "2" },
    { label: "Haveluloto", value: "3" },
    { label: "Vaini", value: "4" },
    { label: "Pangai", value: "5" },
    { label: "Ohonua", value: "6" },
    { label: "Hihifo", value: "7" },
    { label: "Niutoua", value: "8" },
    { label: "Niuafo'ou", value: "9" },
    { label: "Tatakamotonga", value: "10" }
  ],
  27: [
    { label: "Port of Spain", value: "1" },
    { label: "Chaguanas", value: "2" },
    { label: "San Fernando", value: "3" },
    { label: "Arima", value: "4" },
    { label: "Point Fortin", value: "5" },
    { label: "Scarborough", value: "6" },
    { label: "Sangre Grande", value: "7" },
    { label: "Princes Town", value: "8" },
    { label: "Siparia", value: "9" },
    { label: "Rio Claro", value: "10" }
  ],
  191: [
    { label: "Tunis", value: "1" },
    { label: "Sfax", value: "2" },
    { label: "Sousse", value: "3" },
    { label: "Kairouan", value: "4" },
    { label: "Bizerte", value: "5" },
    { label: "Gabès", value: "6" },
    { label: "Ariana", value: "7" },
    { label: "Gafsa", value: "8" },
    { label: "La Marsa", value: "9" },
    { label: "Kasserine", value: "10" }
  ],
  93: [
    { label: "Istanbul", value: "1" },
    { label: "Ankara", value: "2" },
    { label: "Izmir", value: "3" },
    { label: "Bursa", value: "4" },
    { label: "Antalya", value: "5" },
    { label: "Adana", value: "6" },
    { label: "Gaziantep", value: "7" },
    { label: "Konya", value: "8" },
    { label: "Mersin", value: "9" },
    { label: "Kayseri", value: "10" }
  ],
  137: [
    { label: "Ashgabat", value: "1" },
    { label: "Turkmenabat", value: "2" },
    { label: "Dasoguz", value: "3" },
    { label: "Mary", value: "4" },
    { label: "Balkanabat", value: "5" },
    { label: "Bayramaly", value: "6" },
    { label: "Turkmenbashi", value: "7" },
    { label: "Tejen", value: "8" },
    { label: "Atamyrat", value: "9" },
    { label: "Yolöten", value: "10" }
  ],
  410: [
    { label: "Cockburn Town", value: "1" },
    { label: "Cockburn Harbour", value: "2" },
    { label: "Five Cays", value: "3" },
    { label: "Blue Hills", value: "4" },
    { label: "The Bight", value: "5" },
    { label: "Dickenson Bay", value: "6" },
    { label: "Balfour Town", value: "7" },
    { label: "Kew", value: "8" },
    { label: "Monkey River Town", value: "9" },
    { label: "Belle Vue", value: "10" }
  ],
  210: [
    { label: "Funafuti", value: "1" },
    { label: "Vaiaku", value: "2" },
    { label: "Asau", value: "3" },
    { label: "Mualea", value: "4" },
    { label: "Fakaifou", value: "5" },
    { label: "Senala", value: "6" },
    { label: "Tanrake", value: "7" },
    { label: "Tonga", value: "8" },
    { label: "Alapi", value: "9" },
    { label: "Matagi", value: "10" }
  ],
  192: [
    { label: "Kampala", value: "1" },
    { label: "Kira", value: "2" },
    { label: "Nansana", value: "3" },
    { label: "Mbarara", value: "4" },
    { label: "Gulu", value: "5" },
    { label: "Lira", value: "6" },
    { label: "Mbale", value: "7" },
    { label: "Jinja", value: "8" },
    { label: "Bwizibwera", value: "9" },
    { label: "Pakwach", value: "10" }
  ],
  94: [
    { label: "Kyiv", value: "1" },
    { label: "Kharkiv", value: "2" },
    { label: "Odesa", value: "3" },
    { label: "Dnipro", value: "4" },
    { label: "Donetsk", value: "5" },
    { label: "Zaporizhzhia", value: "6" },
    { label: "Lviv", value: "7" },
    { label: "Kryvyi Rih", value: "8" },
    { label: "Mykolaiv", value: "9" },
    { label: "Mariupol", value: "10" }
  ],
  138: [
    { label: "Dubai", value: "1" },
    { label: "Abu Dhabi", value: "2" },
    { label: "Sharjah", value: "3" },
    { label: "Al Ain", value: "4" },
    { label: "Ajman", value: "5" },
    { label: "Ras Al Khaimah", value: "6" },
    { label: "Umm Al-Quwain", value: "7" },
    { label: "Fujairah", value: "8" },
    { label: "Khor Fakkan", value: "9" },
    { label: "Dibba Al-Fujairah", value: "10" }
  ],
  95: [
    { label: "London", value: "1" },
    { label: "Birmingham", value: "2" },
    { label: "Manchester", value: "3" },
    { label: "Glasgow", value: "4" },
    { label: "Liverpool", value: "5" },
    { label: "Newcastle", value: "6" },
    { label: "Sheffield", value: "7" },
    { label: "Bristol", value: "8" },
    { label: "Leeds", value: "9" },
    { label: "Cardiff", value: "10" }
  ],
  1: [
    { label: "New York City", value: "1" },
    { label: "Los Angeles", value: "2" },
    { label: "Chicago", value: "3" },
    { label: "Houston", value: "4" },
    { label: "Phoenix", value: "5" },
    { label: "Philadelphia", value: "6" },
    { label: "San Antonio", value: "7" },
    { label: "San Diego", value: "8" },
    { label: "Dallas", value: "9" },
    { label: "San Jose", value: "10" }
  ],
  28: [
    { label: "Charlotte Amalie", value: "1" },
    { label: "Christiansted", value: "2" },
    { label: "Frederiksted", value: "3" },
    { label: "Anna's Retreat", value: "4" },
    { label: "Charlotte Amalie West", value: "5" },
    { label: "Estate Bovoni", value: "6" },
    { label: "Estate Thomas", value: "7" },
    { label: "Hassel Island", value: "8" },
    { label: "Raphune", value: "9" },
    { label: "Red Hook", value: "10" }
  ],
  41: [
    { label: "Montevideo", value: "1" },
    { label: "Salto", value: "2" },
    { label: "Ciudad de la Costa", value: "3" },
    { label: "Paysandú", value: "4" },
    { label: "Las Piedras", value: "5" },
    { label: "Rivera", value: "6" },
    { label: "Maldonado", value: "7" },
    { label: "Tacuarembó", value: "8" },
    { label: "Melo", value: "9" },
    { label: "Mercedes", value: "10" }
  ],
  139: [
    { label: "Tashkent", value: "1" },
    { label: "Namangan", value: "2" },
    { label: "Samarkand", value: "3" },
    { label: "Andijan", value: "4" },
    { label: "Bukhara", value: "5" },
    { label: "Nukus", value: "6" },
    { label: "Qarshi", value: "7" },
    { label: "Fergana", value: "8" },
    { label: "Jizzakh", value: "9" },
    { label: "Urgench", value: "10" }
  ],
  211: [
    { label: "Port Vila", value: "1" },
    { label: "Luganville", value: "2" },
    { label: "Norsup", value: "3" },
    { label: "Isangel", value: "4" },
    { label: "Sola", value: "5" },
    { label: "Lakatoro", value: "6" },
    { label: "Saratamata", value: "7" },
    { label: "Longana", value: "8" },
    { label: "Ipota", value: "9" },
    { label: "Panama", value: "10" }
  ],
  96: [
    { label: "Vatican City", value: "1" }
  ],
  42: [
    { label: "Caracas", value: "1" },
    { label: "Maracaibo", value: "2" },
    { label: "Valencia", value: "3" },
    { label: "Barquisimeto", value: "4" },
    { label: "Ciudad Guayana", value: "5" },
    { label: "Maracay", value: "6" },
    { label: "San Cristóbal", value: "7" },
    { label: "Barcelona", value: "8" },
    { label: "Maturín", value: "9" },
    { label: "Turmero", value: "10" }
  ],
  140: [
    { label: "Hanoi", value: "1" },
    { label: "Ho Chi Minh City", value: "2" },
    { label: "Haiphong", value: "3" },
    { label: "Can Tho", value: "4" },
    { label: "Da Nang", value: "5" },
    { label: "Bien Hoa", value: "6" },
    { label: "Hue", value: "7" },
    { label: "Nha Trang", value: "8" },
    { label: "Can Tho", value: "9" },
    { label: "Vung Tau", value: "10" }
  ],
  212: [
    { label: "Mata-Utu", value: "1" },
    { label: "Leava", value: "2" },
    { label: "Alele", value: "3" },
    { label: "Haafuasia", value: "4" },
    { label: "Gahi", value: "5" },
    { label: "Kolopelu", value: "6" },
    { label: "Lano", value: "7" },
    { label: "Mou", value: "8" },
    { label: "Futuna", value: "9" },
    { label: "Mala'e", value: "10" }
  ],
  193: [
    { label: "Laayoune", value: "1" },
    { label: "Dakhla", value: "2" },
    { label: "Smara", value: "3" },
    { label: "Es Semara", value: "4" },
    { label: "Auserd", value: "5" },
    { label: "Bir Gandouz", value: "6" },
    { label: "Tifariti", value: "7" },
    { label: "Foum El Oued", value: "8" },
    { label: "Boujdour", value: "9" },
    { label: "El Marsa", value: "10" }
  ],
  141: [
    { label: "Sanaa", value: "1" },
    { label: "Aden", value: "2" },
    { label: "Taiz", value: "3" },
    { label: "Hodeidah", value: "4" },
    { label: "Ibb", value: "5" },
    { label: "Ad Dali", value: "6" },
    { label: "Al Mukalla", value: "7" },
    { label: "Sayyan", value: "8" },
    { label: "Zinjibar", value: "9" },
    { label: "Sadah", value: "10" }
  ],
  194: [
    { label: "Lusaka", value: "1" },
    { label: "Kitwe", value: "2" },
    { label: "Ndola", value: "3" },
    { label: "Kabwe", value: "4" },
    { label: "Chingola", value: "5" },
    { label: "Mufulira", value: "6" },
    { label: "Luanshya", value: "7" },
    { label: "Livingstone", value: "8" },
    { label: "Kasama", value: "9" },
    { label: "Chipata", value: "10" }
  ],
  195: [
    { label: "Harare", value: "1" },
    { label: "Bulawayo", value: "2" },
    { label: "Chitungwiza", value: "3" },
    { label: "Mutare", value: "4" },
    { label: "Gweru", value: "5" },
    { label: "Epworth", value: "6" },
    { label: "Kwekwe", value: "7" },
    { label: "Kadoma", value: "8" },
    { label: "Masvingo", value: "9" },
    { label: "Chinhoyi", value: "10" }
  ]




  // ... (other cities for different countries)
};
