const Constants = {
  URLConstants: {
    LOGINFORM: "/LoginForm",
    DASHBOARD: "/Dashboard",
    Error: "/Error",
    UNAUTHORIZED: "/401",
    STAFFNEW: "/StaffNew",
    STAFFSEARCH: "/StaffSearch",
    STAFFASSIGNBRANCHES: "/StaffAssignBranches",
    STAFFACCESSCREATERIGHTS: "/createRights",
    STAFFACCESSCREATEPROFILES: "/createprofiles",
    STAFFACCESSROLES: "/roles",
    STAFFACCESSMENU: "/menustaff",
    STAFFACCESSREPORTS: "/reports",
    STAFFACCESS: "/staffAccess",
    STAFFACCESSCREATEREPORTS: "/createReports",
    BRANCHNEW: "/branchnew",
    BRANCHSEARCH: "/branchSearch",
    SETTINGREMINDERNEW: "/settingReminderNew",
    SETTINGREMINDERSEARCH: "/settingReminderSearch",
    SETTINGREMINDERVIEW: "/settingReminderView",
    SETTINGREMINDERSET: "/settingReminderSet",
    EMAILNEW: "/emailnew",
    EMAILSEARCH: "/emailSearch",
    EMAILEDIT: "/emailEdit",
    ADDMENU: "/addMenu",
    ADDSUBMENU: "/addSubMenu",
    MENUSEARCH: "/menusearch",
    SITEMAP: "/sitemap",
    MIDOFFICE: "/midoffice",
    APISCONFIGURATION: "/apisConfiguration",
    REDISCONFIGURATION: "/redisConfiguration",
    STATICCONTENTMANAGEMENT: "/staticContentManagement",
    ADMINLOCK: "/adminlock",
    ADMINLOCK2: "/adminlock2",
    LOGUSERS: "/logsuser",
    LOGEMAIL: "/logsemail",
    STAFFACCESSRIGHT: "/staffAccessRight",
    STAFFEDITUSER: "/staffEditUser",
    SITEMAPEDIT: "/sitemapedit",
    SITEMAPADD: "/sitemapadd",
    EDITMENU: "/editmenu",
    EDITBRANCH: "/editbranch",
    ADDPROFILE: "/addprofile",
    EDITPROFILE: "/editprofile",
    ADDCARD: "/addCard",
    SEARCHCARD: "/searchCard",
    EDITCARD: "/editCard",
    VIEWCARD: "/viewCard",
    ADDCARDPAYMENT: "/addCardPayment",
    SEARCHCARDPAYMENT: "/searchCardPayment",
    EDITCARDPAYMENT: "/editCardPayment",
    VIEWCARDPAYMENT: "/viewCardPayment",
    SUPPLIERDETAILS: "/suppliersDeatils",
    SUPPLIERSEARCH: "/supplierSearch",
    SUPPLIERSEARCHEDIT: "/supplierSearchEdit",
    SUPPLIERSEARCHVIEW: "/supplierSearchView",
    OFFLINESUPPLIER: "/suppliersOffline",
    OFFLINESUPPLIERSEARCH: "/supplierOfflineSearch",
    OFFLINESUPPLIERSCHANGEPASSWORD: "/supplierOfflineChangePassword",
    OFFLINESUPPLIEREDIT: "/supplierOfflineSearchEdit",
    OFFLINESUPPLIERVIEW: "/supplierOfflineSearchView",
    OFFLINESUPPLIERVCCSETTING: "/supplierOfflineSearchVccSetting",
    OFFLINESUPPLIERTAXREGISTRATION: "/supplierOfflineSearchTaxRegistration",
    TOOLSADDLEAPTIME: "/toolsAddleaptime",
    TOOLSADDONNEW: "/toolsAddOnNew",
    TOOLSADDONSEARCH: "/toolsAddOnSearch",
    TOOLSBYCOUNTRYBRANCH: "/toolsByCountryBranch",
    TOOLSREWARDSDELIVERY: "/toolsRewardsDelivery",
    TOOLSREWARDSDELIVERYEDIT: "/toolsRewardsDeliveryEdit",
    TOOLSREWARDSDELIVERYVIEW: "/toolsRewardsDeliveryView",
    TOOLSLANGUAGEMANAGER: "/toolsLanguageManager",
    TOOLSPERTRANSACTION: "/toolsPerTransaction",
    TOOLSTOTALTRANSACTION: "/toolsTotalTransaction",
    TOOLSCALCULATOR: "/toolsCalculator",
    TOOLSMATRIX: "/toolsMatrix",
    TOOLSMAPPINGCOUNTRIESAUTO: "/toolsMappingCountriesAuto",
    TOOLSMAPPINGCOUNTRIESAUTOSHOW: "/toolsMappingCountriesAutoShow",
    TOOLSMAPPINGCOUNTRIESMANUAL: "/toolsMappingCountriesManual",
    TOOLSMAPPINGCOUNTRIESMANUALADD: "/toolsMappingCountriesManualAdd",
    TOOLSMAPPINGCOUNTRIESMANUALEDIT: "/toolsMappingCountriesManualEdit",
    TOOLSMAPPINGCOUNTRIESMANUALVIEW: "/toolsMappingCountriesManualView",
    TOOLSMAPPINGCITIESMANUAL: "/toolsMappingCitiesManual",
    TOOLSMAPPINGCITIESMANUALSERACH: "/toolsMappingCitiesManualSearch",
    TOOLSMAPPINGCITIESMANUALEDIT: "/toolsMappingCitiesManualEdit",
    TOOLSMAPPINGCITIESMANUALVIEW: "/toolsMappingCitiesManualView",
    TOOLSMAPPINGCITIESMANUALSUPPLIER: "/toolsMappingCitiesManualSupplier",

    //  Geo Graphical Content
    // Contries

    TOOLSGEOGRAPHICALCONTENTCOUNTRIESADD:
      "/toolsGeographicalContentCountriesAdd",
    TOOLSGEOGRAPHICALCONTENTCOUNTRIESSEARCH:
      "/toolsGeographicalContentCountriesSearch",
    TOOLSGEOGRAPHICALCONTENTCOUNTRIESEDIT:
      "/toolsGeographicalContentCountriesEdit",
    TOOLSGEOGRAPHICALCONTENTCOUNTRIESVIEW:
      "/toolsGeographicalContentCountriesView",

    // Continents

    TOOLSGEOGRAPHICALCONTENTCONTINENTSADD:
      "/toolsGeographicalContentContinentAdd",
    TOOLSGEOGRAPHICALCONTENTCONTINENTSSEARCH:
      "/toolsGeographicalContentContinentSearch",
    TOOLSGEOGRAPHICALCONTENTCONTINENTSEDIT:
      "/toolsGeographicalContentContinentsEdit",
    TOOLSGEOGRAPHICALCONTENTCONTINENTSVIEW:
      "/toolsGeographicalContentContinentsView",

    // Cities

    TOOLSGEOGRAPHICALCONTENTCITIESADD: "/toolsGeographicalContentCitiesAdd",
    TOOLSGEOGRAPHICALCONTENTCITIESSEARCH:
      "/toolsGeographicalContentCitiesSearch",
    TOOLSGEOGRAPHICALCONTENTCITIESEDIT: "/toolsGeographicalContentCitiesEdit",
    TOOLSGEOGRAPHICALCONTENTCITIESVIEW: "/toolsGeographicalContentCitiesView",

    TOOLSGEOGRAPHICALCONTENTCITIES: "/toolsGeographicalContentCities",
    TOOLSGEOGRAPHICALCONTENTCONTINENT: "/toolsGeographicalContentContinent",
    TOOLSMAPPINGHOTELS: "/toolsMappingHotels",
    TOOLSMAPPINGHOTELSMAP: "/toolsMappingHotelsMap",
    TOOLSMAPPINGNATIONALITIESREPORT: "/toolsMappingNationalitiesReport",
    TOOLSMAPPINGNATIONALITIESREPORTSHOW: "/toolsMappingNationalitiesReportShow",
    TOOLSMAPPINGOFFLINESUPPLIERSHOTEL: "/toolsMappingOfflineSuppliersHotel",
    TOOLSMAPPINGOFFLINESUPPLIERSTRANSFER:
      "/toolsMappingOfflineSuppliersTransfer",
    TOOLSMAPPINGOFFLINESUPPLIERSTOURANDACTIVITIES:
      "/toolsMappingOfflineSuppliersTOurAndActivities",
    TOOLSPRESETTEXT: "/toolsPresetText",
    TOOLSPRESETEDIT: "/toolsPresetEdit",

    FLIGHTFLIGHTADDRULES: "/flightFlightAddRules",
    FLIGHTFLIGHTSEARCHRULES: "/flightFlightSearchRules",
    FLIGHTFLIGHTEDITRULES: "/flightFlightEditRules",
    FLIGHTFLIGHTCLONERULES: "/flightFlightCloneRules",
    FLIGHTFLIGHTVIEWRULES: "/flightFlightViewRules",
    FLIGHTFLIGHTPCCADDRULES: "/flightFlightPccAddRules",
    FLIGHTFLIGHTPCCSEARCHRULES: "/flightFlightPccSearchRules",
    FLIGHTEDITOFFICEIDS: "/flightEditOfficeIds",
    FLIGHTVIEWOFFICEIDS: "/flightViewOfficeIds",
    FLIGHTFLIGHTPCCVIEWRULES: "/flightFlightPccViewRules",
    FLIGHTFLIGHTPCCEDITRULES: "/flightFlightPccEditRules",
    FLIGHTFLIGHTQCTADDRULES: "/flightFlightQctAddRules",
    FLIGHTFLIGHTQCTSEARCHRULES: "/flightFlightQctSearchRules",
    FLIGHTFLIGHTQCTEDITRULES: "/flightFlightQctEditRules",
    FLIGHTFLIGHTQCTVIEWRULES: "/flightFlightQctViewRules",
    FLIGHTFLIGHTQCTUPDATELOACATION: "/flightFlightQctUpdateLocation",
    FLIGHTFLIGHTCANCELLATIONADDRULES: "/flightFlightCancellationAddRules",
    FLIGHTFLIGHTCANCELLATIONSEARCHRULES: "/flightFlightCancellationSearchRules",
    FLIGHTFLIGHTCANCELLATIONEDITRULES: "/flightFlightCancellationEditRules",

    VISANEWVISAOFFLINEBOOKING: "/VisaNewVisaOfflineBooking",
    VISASERACHVISAREQUESTS: "/VisaSearchVisaRequests",
    VISASERACHPAYMENTREQUESTS: "/VisaSearchPaymentProof/:id",

    VISASERACHEDITREQUESTS: "/VisaSearchEditRequests/:id",
    VISASERACHVIEWREQUESTS: "/VisaSearchViewRequests/:id",
    VISAEDITPASSPORTIMAGE: "/VisaEditPassportImage/:id",
    VISAEDITPASSPORTIMAGE2: "/VisaEditPassportImage2/:id",
    VISAPERSONALIMAGE: "/VisaPersonalImage/:id",
    VISAEDITRESIDENTPAGE: "/VisaEditResidentPage/:id",
    VISAEDITFLIGHTTICKETPAGE: "/VisaEditFlightTicketPage/:id",
    VISAEDITOTHERIMAGE: "/VisaEditOtherImage/:id",
    VISAUPLOADVISA: "/VisaUploadVisa",
    VISAADDSUPPLIERVISARATES: "/VisaAddSupplierVisaRates",
    VISASEARCHSUPPLIERVISARATES: "/VisaSearchSupplierVisaRates",
    VISAADDCATEGORY: "/VisaAddCategory",
    VISASEARCHCATEGORY: "/VisaSearchCategory",

    MASTERSHOTELSNEW: "/MastersHotelsNew",
    MASTERSHOTELSEDIT: "/MastersHotelsEdit",
    MASTERSHOTELSVIEW: "/MastersHotelsView",
    MASTERSHOTELSSUPPLIERSMAPPING: "/MastersHotelsSuppliersMapping",
    MASTERSHOTELSSEARCH: "/MastersHotelsSearch",
    MASTERSHOTELAMENITIESNEW: "/MastersHotelsAmenitiesNew",
    MASTERSHOTELAMENITIESSEARCH: "/MastersHotelsAmenitiesSearch",
    MASTERSHOTELAMENITIESEDIT: "/MastersHotelsAmenitiesEdit",
    MASTERSHOTELAMENITIESVIEW: "/MastersHotelsAmenitiesView",
    MASTERSHOTELSIMPORTS: "/MastersHotelsImports",
    MASTERSHOTELLOCATIONNEW: "/MastersHotelsLocationNew",
    MASTERSHOTELLOCATIONSEARCH: "/MastersHotelsLocationSearch",
    TRANSFERSLOCATIONSEARCH: "/TransfersLocationSearch",
    MASTERSHOTELLOCATIONSEDIT: "/MastersHotelsLocationEdit",
    MASTERSHOTELLOCATIONSVIEW: "/MastersHotelsLocationView",
    MASTERSROOMVIEWNEW: "/MastersHotelsRoomViewNew",
    MASTERSROOMVIEWSEARCH: "/MastersHotelsRoomViewSearch",
    MASTERSROOMVIEWEDIT: "/MastersHotelsRoomViewEdit",
    MASTERSROOMCATEGORYNEW: "/MastersHotelsRoomCategoryNew",
    MASTERSROOMCATEGORYSEARCH: "/MastersHotelsRoomCategorySearch",
    MASTERSROOMCATEGORYEDIT: "/MastersHotelsRoomCategoryEdit",
    MASTERSINVENTORYROOMCATEGORYNEW: "/MastersInventoryRoomCategoryNew",
    MASTERSINVENTORYROOMCATEGORYSEARCH: "/MastersInventoryRoomCategorySearch",
    MASTERSINVENTORYROOMCATEGORYEDIT: "/MastersInventoryRoomCategoryEdit",
    MASTERSHOTELSMEALBASISMAPPING: "/MastersHotelsMealBasisMapping",
    MASTERSHOTELSMEALBASISNEW: "/MastersHotelsMealBasisNew",
    MASTERSHOTELSMEALBASISSEARCH: "/MastersHotelsMealBasisSearch",
    MASTERSHOTELSMEALBASISEDIT: "/MastersHotelsMealBasisEdit",
    MASTERSHOTELSPREFEREDNEW: "/MastersHotelsPreferedNew",
    MASTERSHOTELSPREFEREDSEARCH: "/MastersHotelsPreferedSearch",
    MASTERSHOTELSSPECIALREQUESTNEW: "/MastersHotelsSpecialRequestNew",
    MASTERSHOTELSSPECIALREQUESTSEARCH: "/MastersHotelsSpecialRequestSerach",
    MASTERSHOTELSSPECIALREQUESTEDIT: "/MastersHotelsSpecialRequestEdit",

    MASTERSTRANSFERSNEW: "/MastersTransferNew",
    MASTERSTRANSFERSSEARCH: "/MastersTransferSearch",
    MASTERSTRANSFERSEDIT: "/MastersTransferEdit",
    MASTERSTRANSFERSVIEW: "/MastersTransferView",
    MASTERSTRANSFERSLOCATIONVIEW: "/MastersTransferLocationView",
    MASTERSTRANSFERSLOCATIONEDIT: "/MastersTransferLocationedit",
    MASTERSTRANSFERSSUPPLIERMAPPING: "/MastersTransferSupplierMapping",
    MASTERSTRANSFERSLOCATIONSNEW: "/MastersTransferLocationsNew",
    MASTERSTRANSFERSLOCATIONSSEARCH: "/MastersTransferLocationsSearch",

    MASTERSTOURSANDACTIVITIESNEW: "/MastersToursAndActivitiesNew",
    MASTERSTOURSANDACTIVITIESSEARCH: "/MastersToursAndActivitiesSearch",
    MASTERSTOURSANDACTIVITIESMAPPING: "/MastersToursAndActivitiesMapping",
    MASTERSTOURSANDACTIVITIESEDIT: "/MastersToursAndActivitiesEdit",
    MASTERSTOURSANDACTIVITIESVIEW: "/MastersToursAndActivitiesView",

    MASTERSSUPPLIEMENTSHOTELNEW: "/MastersSuppliementsHotelNew",
    MASTERSSUPPLIEMENTSHOTELSEARCH: "/MastersSuppliementsHotelSearch",
    MASTERSSUPPLIEMENTSHOTELEDIT: "/MastersSuppliementsHotelEdit",

    MASTERSAIRLINESNEW: "/MastersAirlinesNew",
    MASTERSAIRLINESSEARCH: "/MastersAirlinesSearch",

    MASTERSPREFEREDCITIES: "/MastersPreferedCities",

    MASTERSSUPPLIERSONLINESUPPLIERSSEARCH:
      "/MastersSupplierOnlineSupplierSearch",
    MASTERSSUPPLIERSONLINESUPPLIERSEDIT: "/MastersSupplierOnlineSupplierEdit",
    MASTERSSUPPLIERSONLINESUPPLIERSVIEW: "/MastersSupplierOnlineSupplierView",
    MASTERSSUPPLIERSONLINESUPPLIERSAUTOCHECKCONFIGURATION:
      "/MastersSupplierOnlineSupplierAutoCheckConfiguration",
    SUPPLIERSONLINESUPPLIERSAUTOCHECKCONFIGURATINEDIT:
      "/SupplierOnlineSupplierAutoCheckConfigurationEdit",

    SUPPLIERSONLINESUPPLIERSAUTOCHECKCONFIGURATIONADD:
      "/SupplierOnlineSupplierAutoCheckConfigurationAdd",
    MASTERSSUPPLIERSAUTOCHECKSUPPLIERS: "/MastersSupplierAutoCheckSupplier",
    SUPPLIERSAUTOCHECKSUPPLIERSBUTTON: "/SupplierAutoCheckSupplierButton",

    MASTERSSUPPLIERSOFFLINESUPPLIERSNEW: "/MastersSupplierOffineSupplierNew",
    MASTERSSUPPLIERSOFFLINESUPPLIERSSEARCH:
      "/MastersSupplierOffineSupplierSearch",
    MASTERSSUPPLIERSOFFLINESUPPLIERSCHANGEPASSWORD:
      "/MastersSupplierOffineSupplierChangePassword",
    MASTERSSUPPLIERSOFFLINESUPPLIERSEDIT: "/MastersSupplierOffineSupplierEdit",
    MASTERSSUPPLIERSOFFLINESUPPLIERSVIEW: "/MastersSupplierOffineSupplierView",
    MASTERSSUPPLIERSOFFLINESUPPLIERSVCCSETTING:
      "/MastersSupplierOffineSupplierVccSetting",
    MASTERSSUPPLIERSOFFLINESUPPLIERSTAXREGISTRATION:
      "/MastersSupplierOffineSupplierTaxRegistration",

    MASTERSTRAVELCLASSNEW: "/MastersTravelClassNew",
    MASTERSTRAVELCLASSSEARCH: "/MastersTravelClassSearch",

    MASTERSMARKUPPROFILENEW: "/MastersMarkUpProfileNew",
    MASTERSMARKUPPROFILESEARCH: "/MastersMarkUpProfileSearch",
    MASTERSMARKUPPROFILEEDIT: "/MastersMarkUpProfileEdit",

    MASTERSPAYMENTSEARCH: "/payment-gateways",
    MASTERSPAYMENTNEW: "/payment-gateways/add",
    MASTERSPAYMENTEDIT: "/payment-gateways/edit",
    MASTERSPAYMENTVIEW: "/payment-gateways/view",
    MASTERSPAYMENTPERTRANSACTIONLIMIT: "/MastersPaymentPerTransactionLimit",
    MASTERSPAYMENTTOTALLIMIT: "/MastersPaymentTotalLimit",
    MASTERSAIRCRAFTSNEW: "/MastersAircraftsNew",
    MASTERSAIRCRAFTSSEARCH: "/MastersAircraftsSearch",

    MASTERSBANKSNEW: "/MastersBankSNew",
    MASTERSBANKSSEARCH: "/MastersBankSSearch",
    MASTERSBANKSEDIT: "/MastersBankSEdit",

    MASTERSCURRENCIESNEW: "/MastersCurrenciesNew",
    MASTERSCURRENCIESEDIT: "/MastersCurrenciesEdit",
    MASTERSCURRENCIESSEARCH: "/MastersCurrenciesSearch",

    MASTERSTAXESNEW: "/MastersTaxesNew",
    MASTERSTAXESSEARCH: "/MastersTaxesSearch",

    MASTERSTAXMASTERNEW: "/MastersTaxMasterNew",
    MASTERSTAXMASTERSEARCh: "/MastersTaxMasterSearch",
    MASTERSTAXMASTEREDIT: "/MastersTaxMasterEdit",

    MASTERSTAXCONFIGURATIONADD: "/MastersTaxConfigurationAdd",
    MASTERSTAXCONFIGURATIONSEARCH: "/MastersTaxConfigurationSearch",
    MASTERSTAXCONFIGURATIONEDIT: "/MastersTaxConfigurationEdit",

    MASTERSLOYALITYPROGRAMTIERSNEW: "/MastersLoyalityProgramTiersNew",
    MASTERSLOYALITYPROGRAMTIERSSEARCH: "/MastersLoyalityProgramTiersSearch",
    MASTERSLOYALITYPROGRAMTIERSEDIT: "/MastersLoyalityProgramTiersEdit",

    MASTERSLOYALITYPROGRAMREWARDSNEW: "/MastersLoyalityProgramRewardsNew",
    MASTERSLOYALITYPROGRAMREWARDSSEARCH: "/MastersLoyalityProgramRewardsSearch",
    MASTERSLOYALITYPROGRAMREWARDSEDIT: "/MastersLoyalityProgramRewardsEdit",
    MASTERSLOYALITYPROGRAMREWARDSVIEW: "/MastersLoyalityProgramRewardsView",

    MASTERSPACKAGESSEARCH: "/MastersPackagesSearch",
    MASTERSPACKAGESVIEW: "/MastersPackagesView",
    MASTERSPACKAGESADD: "/MastersPackagesAdd",
    MASTERSPACKAGESEDIT: "/MastersPackagesEdit",

    MASTERSOFFERCODESEARCH: "/MastersOfferCodesSearch",
    MASTERSOFFERCODEEDIT: "/MastersOfferCodesEdit",

    MASTERSVEHICLESTYPENEW: "/MastersVehicleTypeNew",
    MASTERSVEHICLESTYPESEARCH: "/MastersVehicleTypeSearch",
    MASTERSVEHICLESTYPEEDIT: "/MastersVehicleTypeEdit",

    MASTERSVEHICLESINVENTORYNEW: "/MastersVehicleInventoryNew",
    MASTERSVEHICLESINVENTORYSEARCH: "/MastersVehicleInventorySearch",
    MASTERSVEHICLESINVENTORYEDIT: "/MastersVehicleInventoryEdit",

    CONTRACTSHOTELSALLOTMENT: "/ContractsHotelsAllotment",
    CONTRACTSHOTELSALLOTMENTBUTTON: "/ContractsHotelsAllotmentButton",

    CONTRACTSHOTELSDYNAMICALLOTMENTNEW: "/ContractsHotelsDynamicAllotmentNew",
    CONTRACTSHOTELSDYNAMICALLOTMENTSEARCH:
      "/ContractsHotelsDynamicAllotmentSearch",
    CONTRACTSHOTELSDYNAMICALLOTMENTEDIT: "/ContractsHotelsDynamicAllotmentEdit",

    CONTRACTSHOTELSOFFERSANDDISCOUNTSNEW:
      "/ContractsHotelsOffersAndDiscountsNew",
    CONTRACTSHOTELSOFFERSANDDISCOUNTSSEARCH:
      "/ContractsHotelsOffersAndDiscountsSearch",
    CONTRACTSHOTELSOFFERSANDDISCOUNTSSEARCHBUTTON:
      "/ContractsHotelsOffersAndDiscountsSearchButton",

    CONTRACTSHOTELSRATESSEARCH: "/ContractsHotelsRatesSearch",
    CONTRACTSHOTELSRATESSEARCHBUTTON: "/ContractsHotelsRatesSearchButton",
    CONTRACTSHOTELSRATESUSERLOGS: "/ContractsHotelsRatesUserLogs",

    CONTRACTSTRANSFERSRATESSEARCH: "/ContractsTransfersRatesSearch",
    CONTRACTSTRANSFERSRATESSEARCHBUTTON: "/ContractsTransfersRatesSearchButton",
    CONTRACTSTRANSFERSRATESVIEWSTOPSALE: "/ContractsTransfersRatesViewStopSale",
    CONTRACTSTRANSFERSRATESADDSTOPSALE: "/ContractsTransfersRatesAddStopSale",
    CONTRACTSTRANSFERSRATESCANCELPOLICY: "/ContractsTransfersRatesCancelPolicy",
    CONTRACADDTSTRANSFERSRATESCANCELPOLICY:
      "/ContractsAddTransfersRatesCancelPolicy",
    CONTRACTSTRANSFERSRATESSEARCHTRANFERLIST:
      "/ContractsTransfersRatesSerachTranferList",
    CONTRACTSEDITTRANSFERSRATESLIST: "/ContractsEditTransfersRatesList",
    CONTRACTSADDTRANSFERSRATESLIST: "/ContractsAddTransfersRatesList",
    CONTRACTSTOURSANDACTIVITIESRATESLIST:
      "/ContractsToursAndActivitiesRatesList",
    CONTRACTSTOURSANDACTIVITIESADDRATES: "/ContractsToursAndActivitiesAddRates",
    CONTRACTSFLIGHTSSUPPLIERMAPPING: "/ContractsFlightsSupplierMapping",
    CONTRACTSFLIGHTSADDRATES: "/ContractsFlightsAddRates",
    CONTRACTSFLIGHTSADDRATESSEARCH: "/ContractsFlightsAddRatesSearch",
    CONTRACTSFLIGHTSSEARCH: "/ContractsFlightsSearch",
    CONTRACTSFLIGHTSSEARCHBUTTON: "/ContractsFlightsSearchButton",
    CONTRACTSFLIGHTSADDLIST: "/ContractsFlightsAddList",
    CONTRACTSFLIGHTSEDITLIST: "/ContractsFlightsEditList",
    CONTRACTSFLIGHTSVIEWLIST: "/ContractsFlightsViewList",

    HOTELINVENTORYAPP: "/hotelInventoryApp",
    HOTELINVENTORYAPPALLOCATION: "/hotelInventoryAppAllocation",
    HOTELINVENTORYAPPSELLPOLICY: "/hotelInventorySellPolicy",
    HOTELINVENTORYAPPDASHBOARD: "/hotelInventoryDashboard",
    HOTELINVENTORYAPPBOOKINGDETAILS: "/hotelInventoryBookingDetails",
    HOTELINVENTORYAPPPOLICIES: "/hotelInventoryPolicies",
    HOTELINVENTORYAPPSUPPLIEMENTS: "/hotelInventorySuppliements",
    HOTELINVENTORYAPPMANAGESEASON: "/hotelInventoryManageSeason",
    HOTELINVENTORYAPPEXTRABED: "/hotelInventoryExtraBed",
    HOTELINVENTORYAPPCONTRACTS: "/hotelInventoryContracts",
    HOTELINVENTORYAPPTARIFFWRITER: "/hotelInventoryTariffWriter",
    HOTELINVENTORYAPPARRIVAL: "/hotelInventoryArrival",
    HOTELINVENTORYAPPCREATEOFFER: "/hotelInventoryCreateOffer",
    HOTELINVENTORYAPPEDITOFFER: "/hotelInventoryEditOffer",
    HOTELINVENTORYAPPDELETERATES: "/hotelInventoryDeleteRates",
    HOTELINVENTORYAPPEXCLUDECOUNTRY: "/hotelInventoryExcludeCountry",
    HOTELINVENTORYAPPEXCLUDENATIONALITY: "/hotelInventoryExcludeNationality",
    HOTELINVENTORYAPPEXPIRINGRATES: "/hotelInventoryExpiringRates",
    HOTELINVENTORYAPPHOTELSETTING: "/hotelInventoryHotelSetting",
    HOTELINVENTORYAPPHOTELROOMMAPPING: "/hotelInventoryHotelRoomMapping",
    HOTELINVENTORYAPPMASTERADD: "/hotelInventoryMasterAdd",
    HOTELINVENTORYAPPMASTERSEARCH: "/hotelInventoryMasterSearch",
    HOTELINVENTORYAPPOLDROOMRATES: "/hotelInventoryOldRoomRates",
    HOTELINVENTORYAPPRECENTCHANGES: "/hotelInventoryRecentChanges",
    HOTELINVENTORYAPPRECENTCHANGESSEARCH: "/hotelInventoryRecentChangesSearch",
    HOTELINVENTORYAPPSEARCHOFFER: "/hotelInventorySearchOffer",
    HOTELSEXTRANETLIST: "/hotelExtranetHotels",
    HOTELSEXTRANETADD: "/hotelExtranetHotelsAdd",
    HOTELSEXTRANETVIEW: "/hotelExtranetHotelsView",
    HOTELSEXTRANETEDIT: "/hotelExtranetHotelsEdit",
    HOTELSEXTRANETROOMSLIST: "/hotelExtranetRooms",
    HOTELSEXTRANETROOMSADD: "/hotelExtranetRoomsAdd",
    HOTELSEXTRANETROOMSVIEW: "/hotelExtranetRoomsView",
    HOTELSEXTRANETROOMSEDIT: "/hotelExtranetRoomsEdit",
    HOTELSEXTRANETCONTRACTSLIST: "/hotelExtranetContracts",
    HOTELSEXTRANETCONTRACTSADD: "/hotelExtranetContractsAdd",
    HOTELSEXTRANETCONTRACTSVIEW: "/hotelExtranetContractsView",
    HOTELSEXTRANETCONTRACTSEDIT: "/hotelExtranetContractsEdit",
    HOTELSEXTRANETRATESLIST: "/hotelExtranetRates",
    HOTELSEXTRANETRATESADD: "/hotelExtranetRatesAdd",
    HOTELSEXTRANETSEASONSLIST: "/hotelExtranetSeasons",
    HOTELSEXTRANETSEASONSADD: "/hotelExtranetSeasonsAdd",
    HOTELSEXTRANETSEASONSVIEW: "/hotelExtranetSeasonsView",
    HOTELSEXTRANETSEASONSEDIT: "/hotelExtranetSeasonsEdit",
    HOTELSEXTRANETRATESVIEW: "/hotelExtranetRatesView",
    HOTELSEXTRANETRATESEDIT: "/hotelExtranetRatesEdit",
    HOTELSEXTRANETALLOTMENTSLIST: "/hotelExtranetAllotments",
    HOTELSEXTRANETALLOTMENTSADD: "/hotelExtranetAllotmentsAdd",
    HOTELSEXTRANETALLOTMENTSVIEW: "/hotelExtranetAllotmentsView",
    HOTELSEXTRANETALLOTMENTSEDIT: "/hotelExtranetAllotmentsEdit",
    HOTELSEXTRANETRESTRICTIONSLIST: "/hotelExtranetRestrictions",
    HOTELSEXTRANETRESTRICTIONSADD: "/hotelExtranetRestrictionsAdd",
    HOTELSEXTRANETRESTRICTIONSVIEW: "/hotelExtranetRestrictionsView",
    HOTELSEXTRANETRESTRICTIONSEDIT: "/hotelExtranetRestrictionsEdit",
    HOTELSEXTRANETBLACKOUTSLIST: "/hotelExtranetBlackouts",
    HOTELSEXTRANETBLACKOUTSADD: "/hotelExtranetBlackoutsAdd",
    HOTELSEXTRANETBLACKOUTSVIEW: "/hotelExtranetBlackoutsView",
    HOTELSEXTRANETBLACKOUTSEDIT: "/hotelExtranetBlackoutsEdit",
    HOTELSEXTRANETPROMOTIONSLIST: "/hotelExtranetPromotions",
    HOTELSEXTRANETPROMOTIONSADD: "/hotelExtranetPromotionsAdd",
    HOTELSEXTRANETPROMOTIONSVIEW: "/hotelExtranetPromotionsView",
    HOTELSEXTRANETPROMOTIONSEDIT: "/hotelExtranetPromotionsEdit",
    HOTELSEXTRANETMEDIALIST: "/hotelExtranetMedia",
    HOTELSEXTRANETMEDIAADD: "/hotelExtranetMediaAdd",
    HOTELSEXTRANETMEDIAVIEW: "/hotelExtranetMediaView",
    HOTELSEXTRANETMEDIAEDIT: "/hotelExtranetMediaEdit",
    HOTELSEXTRANETREADINESSLIST: "/hotelExtranetReadiness",

    HOTELSEXTRANETDASHBOARD: "/hotelExtranetDashboard",

    SERACHBOOKINGS: "/SearchBookings",
    UPDATEBOOKINGS: "/edit-booking/:bookingId",
    BOOKINGSVIEWBOOKING: "/BookingsViewBookings",
    BOOKINGSTABLEPAGE: "/BookingsTablePage",
    BOOKINGSMODIFYTABLEPAGE: "/BookingsModifyTablePage",
    GOTOMODIFYBOOKING: "/GotoModifyBooking",
    BOOKINGSTABLEPAGEPRINTVOUCHER: "/BookingsTablePagePrintVoucher",
    BOOKINGSTABLEPAGEPRINTINVOICE: "/BookingsTablePagePrintInvoice",
    BOOKINGSREMINDERNEW: "/BookingsReminderNew",
    BOOKINGSREMINDERSEARCH: "/BookingsReminderSearch",
    BOOKINGSREMINDERSVIEW: "/BookingsReminderView",
    BOOKINGSREMINDERSSET: "/BookingsReminderSet",

    BOOKINGSNEWONLINEBOOKING: "/BookingsNewOnlineBooking",
    BOOKINGSREASSIGNBOOKING: "/BookingsRe AssignBooking",
    BOOKINGSRECONCILATIONAUTO: "/BookingsReConcilationAuto",
    BOOKINGSRECONCILATIONMANUAL: "/BookingsReConcilationManual",
    BOOKINGSRECONCILATIONMANUALFLIGHTS: "/BookingsReConcilationManualFlights",

    BOOKINGSNEWOFFLINEBOOKINGTOUR: "/BookingsNewOfflineBookingTour",
    BOOKINGSADDOFFLINEGROUPBOOKING: "/BookingsAddOfflineGroupBooking",
    BOOKINGSADDOFFLINEMISC: "/BookingsAddOfflineMisc",
    BOOKINGSADDOFFLINEMISCSERVICES: "/BookingsAddOfflineMiscServices",
    BOOKINGSADDOFFLINETRANSFER: "/BookingsAddOfflineTransfer",
    BOOKINGSADDOFFLINEFLIGHT: "/BookingsAddOfflineFlight",
    BOOKINGSADDOFFLINEHOTELS: "/BookingsAddOfflineHotels",
    BOOKINGSADDOFFLINEHOTELSINNER: "/BookingsAddOfflineHotelsInner",

    CUSTOMERSAGENTSNEW: "/CustomersAgentsNew",
    CUSTOMERSAGENTSEDIT: "/CustomersAgentsEdit",
    CUSTOMERAGENTSUBUSERSEARCH: "/customeragentSubUserSearch",
    CUSTOMERAGENTSUBUSERNEW: "/CustomersAgentSubUserNew",
    CUSTOMERAGENTSUBUSEREDIT: "/CustomersAgentSubUserEdit",
    CUSTOMERSAGENTSVIEW: "/CustomersAgentsView",
    CUSTOMERSAGENTSEXCLUDECOUNTRIES: "/CustomersAgentsExcludeCountries",
    CUSTOMERSAGENTSCHANGEPASSWORD: "/CustomersAgentsChangePassword",
    CUSTOMERSAGENTSONLINESUPPLIERSETTING:
      "/CustomersAgentsOnlineSupplierSetting",
    CUSTOMERSAGENTSONLINESUPPLIERSERVICETAXSETTING:
      "/CustomersAgentsOnlineSupplierServiceTaxSetting",
    CUSTOMERSAGENTSOFFLINESUPPLIERSETTING:
      "/CustomersAgentsOfflineSupplierSetting",
    CUSTOMERSAGENTSSEARCH: "/CustomersAgentsSearch",
    CUSTOMERSAGENTSSEARCHBUTTON: "/CustomersAgentsSearchButton",
    CUSTOMERSAGENTSINVOICINGRULES: "/CustomersAgentsInvoicingRules",
    CUSTOMERSAGENTSASSIGNPAYEMENTGATEWAY:
      "/CustomersAgentsAssignPayementGateway",
    CUSTOMERSAGENTSREPORTACESSSETTING: "/CustomersAgentsReportAcessSetting",
    CUSTOMERSAGENTSLOYALITYTIERSETTING: "/CustomersAgentLoyalityTierSetting",
    CUSTOMERSAGENTSTAXREGISTRATION: "/CustomersAgentTaxRegistration",
    CUSTOMERSAGENTSCREDITLOG: "/CustomersAgentCreditLog",
    CUSTOMERSAGENTSCREDITVIEW: "/CustomersAgentCreditView",
    CUSTOMERSAGENTSCREDITLIMIT: "/CustomersAgentCreditLimit",
    CUSTOMERSAGENTSASSIGNPAYEMENTGATEWAYLOGS:
      "/CustomersAgentPayementgatewayLogs",
    CUSTOMERSAGENTSLASTLOGIN: "/CustomersAgentLastLogin",
    CUSTOMERSAGENTSSEARCHUSERS: "/CustomersAgentSearchUsers",
    CUSTOMERSAGENTSSEARCHCHANGEPASSWORD: "/CustomersAgentSearchChangePassword",
    CUSTOMERSAGENTSEDITUSERDETAILS: "/CustomersAgentEditUserDetails",
    CUSTOMERSAGENTSADVANCEONLINESETTING: "/CustomersAgentAdvanceOnlineSetting",
    CUSTOMERSAGENTSADVANCEOFFLINESETTING:
      "/CustomersAgentAdvanceOfflineSetting",
    CUSTOMERSAGENTSRATEPROFILE: "/CustomersAgentRateProfile",
    CUSTOMERSAGENTSEDITRATEPROFILE: "/CustomersAgentEditRateProfile",
    CUSTOMERSB2C: "/CustomersB2C",
    CUSTOMERSB2CNEW: "/CustomersB2CNew",
    CUSTOMERSB2CSEARCH: "/CustomersB2CSearch",
    CUSTOMERSB2CEDIT: "/CustomersB2CEdit",
    CUSTOMERSB2CVIEW: "/CustomersB2CVIEW",

    MESSAGESNEW: "/MessagesNew",
    MESSAGESINBOX: "/MessagesInbox",
    MESSAGESINBOXREPLY: "/MessagesInboxReply",
    MESSAGESINBOXEDIT: "/MessagesInboxEdit",
    MESSAGESOUTBOX: "/MessagesOutbox",
    MESSAGESMASSMAILSUBSCRIBERNEW: "/MessagesMassMailSubscribersNew",
    MESSAGESMASSMAILSUBSCRIBEREDIT: "/MessagesMassMailSubscribersEdit",
    MESSAGESMASSMAILSUBSCRIBERVIEW: "/MessagesMassMailSubscribersView",
    MESSAGESMASSMAILSUBSCRIBERSEARCH: "/MessagesMassMailSubscribersSearch",
    MESSAGESMASSMAILSUBSCRIBERGROUPNEW: "/MessagesMassMailSubscribersGroupNew",
    MESSAGESMASSMAILSUBSCRIBERGROUPEDIT:
      "/MessagesMassMailSubscribersGroupEdit",
    MESSAGESMASSMAILSUBSCRIBERGROUPVIEW:
      "/MessagesMassMailSubscribersGroupView",
    MESSAGESMASSMAILSUBSCRIBERGROUPSEARCH:
      "/MessagesMassMailSubscribersGroupSearch",
    MESSAGESADDSUBSCRIBERS: "/MessagesAddSubscribers",
    MESSAGESIMPORTCSV: "/MessagesImportCSV",
    MESSAGESMASSMAILCAMPAIGNANALYSIS: "/MessagesMassMailCampaignAnalysis",
    MESSAGESMASSMAILCAMPAIGNANSETTING: "/MessagesMassMailCampaignSetting",
    MESSAGESMASSMAILCAMPAIGNANSEARCH: "/MessagesMassMailCampaignSearch",
    MESSAGESMASSMAILCAMPAIGNANNEW: "/MessagesMassMailCampaignNew",
    MESSAGESMASSMAILCAMPAIGNANSTEP2: "/MessagesMassMailCampaignStep2",
    MESSAGESMASSMAILCAMPAIGNANSTEP3: "/MessagesMassMailCampaignStep3",
    MESSAGESMASSMAILCAMPAIGNANSTEP4: "/MessagesMassMailCampaignStep4",
    MESSAGESMASSMAILCAMPAIGNANSTEP5: "/MessagesMassMailCampaignStep5",

    ACCOUNTSAGENTRECIEPTNEW: "/AccountsAgentRecieptNew",
    ACCOUNTSAGENTRECIEPTSEARCH: "/AccountsAgentRecieptSearch",
    ACCOUNTSAGENTRECIEPTEDIT: "/AccountsAgentRecieptEdit",
    ACCOUNTSAGENTRECIEPTVIEW: "/AccountsAgentRecieptView",
    ACCOUNTSAGENTRECIEPTALLOCATION: "/AccountsAgentRecieptAllocation",
    ACCOUNTSAGENTRECIEPTPARTIALALLOCATION:
      "/AccountsAgentRecieptPartialAllocation",
    ACCOUNTSAGENTRECIEPTBOOKINGID: "/AccountsAgentRecieptBookingId",
    ACCOUNTSAGENTCREDITNEW: "/AccountsAgentCreditNew",
    ACCOUNTSAGENTCREDITSEARCH: "/AccountsAgentCreditSearch",
    ACCOUNTSAGENTCREDITBOOKINGID: "/AccountsAgentCreditBookingId",
    ACCOUNTSAGENTCREDITVIEW: "/AccountsAgentCreditView",

    ACCOUNTSAGENTDEBITNEW: "/AccountsAgentDebitNew",
    ACCOUNTSAGENTDEBITSEARCH: "/AccountsAgentDebitSearch",
    ACCOUNTSAGENTDEBITBOOKINGID: "/AccountsAgentDebitBookingId",
    ACCOUNTSAGENTDEBITVIEW: "/AccountsAgentDebitView",

    ACCOUNTSTAXSETUPTAXMASTERNEW: "/AccountsTaxSetupTaxMasterNew",
    ACCOUNTSTAXSETUPTAXMASTERSEARCH: "/AccountsTaxSetupTaxMasterSearch",
    ACCOUNTSTAXSETUPTAXMASTEREDIT: "/AccountsTaxSetupTaxMasterEdit",

    ACCOUNTSTAXSETUPTAXCONFUGRATIONNEW: "/AccountsTaxSetupTaxConfigurationNew",
    ACCOUNTSTAXSETUPTAXCONFUGRATIONSEARCH:
      "/AccountsTaxSetupTaxConfigurationSearch",
    ACCOUNTSTAXSETUPTAXCONFUGRATIONEDIT:
      "/AccountsTaxSetupTaxConfigurationEdit",

    ACCOUNTSSUPPLIERSPAYMENTNEW: "/AccountsSuppliersPaymentNew",
    ACCOUNTSSUPPLIERSPAYMENTSEARCH: "/AccountsSuppliersPaymentSearch",
    ACCOUNTSSUPPLIERSPAYMENTEDIT: "/AccountsSuppliersPaymentEdit",
    ACCOUNTSSUPPLIERSPAYMENTVIEW: "/AccountsSuppliersPaymentView",
    ACCOUNTSSUPPLIERSPAYMENTALLOCATION: "/AccountsSuppliersPaymentAllocation",
    ACCOUNTSSUPPLIERSPAYMENTBOOKINGBYID: "/AccountsSuppliersPaymentBookingByID",

    REPORTSMAPPINGDESTINATION: "/ReportsMappingDestination",

    REPORTSOPERATIONSBOOKINGREPORT: "/ReportsOperationsBookingReport",
    REPORTSOPERATIONSAGENTSEARCHLOGS: "/ReportsOperationsAgentSearchLogs",
    REPORTSOPERATIONSAGENTSEARCHLOGSVIEW:
      "/ReportsOperationsAgentSearchLogsView",
    REPORTSOPERATIONSVOUCHER: "/ReportsOperationsVoucher",
    REPORTSOPERATIONSVOUCHERPRINT: "/ReportsOperationsVoucherPrint",
    REPORTSOPERATIONSDAILYROE: "/ReportsOperationsDailyRoe",
    REPORTSOPERATIONSLOYALITYPROGRAM: "/ReportsOperationsLoyalityProgram",
    REPORTSOPERATIONSREMINDER: "/ReportsOperationsReminder",

    REPORTSMANAGEMENTSALESCOMPARISON: "/ReportsManagementSalesComparison",
    REPORTSMANAGEMENTSALESMANAGERREPORT: "/ReportsManagementSalesManagerReport",
    REPORTSMANAGEMENTBOOKINGBYSUPPLIERBYSTATUS:
      "/ReportsManagementBookingBySupplierByStatus",
    REPORTSMANAGEMENTBOOKINGBYSUPPLIERBYNIGHTS:
      "/ReportsManagementBookingBySupplierByNights",
    REPORTSMANAGEMENTBOOKINGBYSUPPLIERBYPROFILE:
      "/ReportsManagementBookingBySupplierByProfile",

    REPORTSMANAGEMENTBUISNESSBYAGENT: "/ReportsManagementBuisnessByAgent",
    REPORTSMANAGEMENTBUISNESSBYHOTEL: "/ReportsManagementBuisnessByHotel",
    REPORTSMANAGEMENTBUISNESSBYCITY: "/ReportsManagementBuisnessByCity",
    REPORTSMANAGEMENTBUISNESSBYCOUNTRY: "/ReportsManagementBuisnessByCountry",
    REPORTSMANAGEMENTBUISNESSBYOFFLINESUPPLIER:
      "/ReportsManagementBuisnessByOfflineSupplier",
    REPORTSMANAGEMENTBUISNESSBYONLINESUPPLIER:
      "/ReportsManagementBuisnessByOnlineSupplier",

    REPORTSACCOUNTSDAILYSALES: "/ReportsAccountsDailySales",
    REPORTSACCOUNTSCUSTOMERSTATEMENT: "/ReportsAccountsCustomerStatement",
    REPORTSACCOUNTSOUTSTANDINGCUSTOMER: "/ReportsAccountsOutstandingCustomer",
    REPORTSACCOUNTSOUTSTANDINGSUPPLIER: "/ReportsAccountsOutstandingSupplier",
    REPORTSACCOUNTSINVOICES: "/ReportsAccountsInvoices",
    REPORTSACCOUNTSAGENTRECIEPTS: "/ReportsAccountsAgentReciepts",
    REPORTSACCOUNTSAGENTRECIEPTSSUMMARY: "/ReportsAccountsAgentRecieptsSummary",
    REPORTSACCOUNTSSUPPLIERPAYMENTS: "/ReportsAccountsSupplierPayments",
    REPORTSACCOUNTSTAX: "/ReportsAccountsTax",
    REPORTSACCOUNTSCOMMISSION: "/ReportsAccountsCommission",
    REPORTSACCOUNTSPAYMENTGATEWAYBOOKINGS:
      "/ReportsAccountsPaymentGatewayBookings",
    REPORTSACCOUNTSAGENTGLOBALSTATEMENT: "/ReportsAccountsAgentGlobalStatement",
    REPORTSACCOUNTSGLOBALCUSTOMERREPORT: "/ReportsAccountsGlobalCustomerReport",
    REPORTSACCOUNTSSUPPLIERSTATEMENTONLINESUPPLIER:
      "/ReportsAccountsSupplierStatementOnlineSupplier",
    REPORTSACCOUNTSSUPPLIERSTATEMENTOFFLINESUPPLIER:
      "/ReportsAccountsSupplierStatementOfflineSupplier",
  },

  FontConstants: {
    FONTMON: "MONTSERRAT",
  },
};

export default Constants;
