export const FETCH_COUNTRIES_DATA_REQUEST = "FETCH_COUNTRIES_DATA_REQUEST";
export const FETCH_COUNTRIES_DATA_REQUEST_FAIL =
  "FETCH_COUNTRIES_DATA_REQUEST_FAIL";
export const FETCH_COUNTRIES_DATA_REQUEST_SUCCESS =
  "FETCH_COUNTRIES_DATA_REQUEST_SUCCESS";
export const FETCH_COUNTRIES_DATA_REQUEST_ERROR =
  "FETCH_COUNTRIES_DATA_REQUEST_ERROR";

  //.. Currencies COnstants...//
export const GET_CURRENCIES_REQUEST = "GET_CURRENCIES_REQUEST";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILURE = "GET_CURRENCIES_FAILURE";
export const GET_CURRENCIES_ERROR = "GET_CURRENCIES_ERROR";

//..Offline Supplier Constants...//
export const GET_OFFLINE_SUPPLIER_REQUEST = "GET_OFFLINE_SUPPLIER_REQUEST";
export const GET_OFFLINE_SUPPLIER_SUCCESS = "GET_OFFLINE_SUPPLIER_SUCCESS";
export const GET_OFFLINE_SUPPLIER_FAILURE = "GET_OFFLINE_SUPPLIER_FAILURE";
export const GET_OFFLINE_SUPPLIER_ERROR = "GET_OFFLINE_SUPPLIER_ERROR";


