export const FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST =
  "FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST";
export const FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST_FAIL =
  "FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST_FAIL";
export const FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST_SUCCESS =
  "FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST_SUCCESS";
export const FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST_ERROR =
  "FETCH_ALL_VISA_CATEGORIES_DATA_REQUEST_ERROR";

//... Add Visa Category...//
export const ADD_VISA_CATEGORY_DATA_REQUEST = "ADD_VISA_CATEGORY_DATA_REQUEST";
export const ADD_VISA_CATEGORY_DATA_REQUEST_FAIL =
  "ADD_VISA_CATEGORY_DATA_REQUEST_FAIL";
export const ADD_VISA_CATEGORY_DATA_REQUEST_SUCCESS =
  "ADD_VISA_CATEGORY_DATA_REQUEST_SUCCESS";
export const ADD_VISA_CATEGORY_DATA_REQUEST_ERROR =
  "ADD_VISA_CATEGORY_DATA_REQUEST_ERROR";


  //..Get Visa Category Rate Edit...//
  export const EDIT_VISA_CATEGORY_DATA_REQUEST =
  "EDIT_VISA_CATEGORY_DATA_REQUEST";
  export const EDIT_VISA_CATEGORY_DATA_REQUEST_FAIL =
  "EDIT_VISA_CATEGORY_DATA_REQUEST_FAIL";
  export const EDIT_VISA_CATEGORY_DATA_REQUEST_SUCCESS =
  "EDIT_VISA_CATEGORY_DATA_REQUEST_SUCCESS";
  export const EDIT_VISA_CATEGORY_DATA_REQUEST_ERROR =
  "EDIT_VISA_CATEGORY_DATA_REQUEST_ERROR";


//....ADD SUPPLIER VISA RATE MODULE...//

//..Add Supplier Visa Rate Child...//

export const ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST =
  "ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST";
export const ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST_FAIL =
  "ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST_FAIL";
export const ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST_SUCCESS =
  "ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST_SUCCESS";
export const ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST_ERROR =
  "ADD_SUPPLIER_VISA_RATE_CHILD_DATA_REQUEST_ERROR";

//..Add Supplier Visa Rate Main...//
export const ADD_SUPPLIER_VISA_RATE_DATA_REQUEST =
  "ADD_SUPPLIER_VISA_RATE_DATA_REQUEST";
export const ADD_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL =
  "ADD_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL";
export const ADD_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS =
  "ADD_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS";
export const ADD_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR =
  "ADD_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR";

//..Get Supplier Visa Rate Main...//
export const GET_SUPPLIER_VISA_RATE_DATA_REQUEST =
  "GET_SUPPLIER_VISA_RATE_DATA_REQUEST";
export const GET_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL =
  "GET_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL";
export const GET_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS =
  "GET_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS";
export const GET_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR =
  "GET_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR";


  //..Del Supplier Visa Rate Main...//
export const DEL_SUPPLIER_VISA_RATE_DATA_REQUEST =
"DEL_SUPPLIER_VISA_RATE_DATA_REQUEST";
export const DEL_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL =
"DEL_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL";
export const DEL_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS =
"DEL_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS";
export const DEL_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR =
"DEL_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR";


  //..Get Supplier Visa Rate Edit...//
  export const EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST =
  "EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST";
  export const EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL =
  "EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST_FAIL";
  export const EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS =
  "EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST_SUCCESS";
  export const EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR =
  "EDIT_SUPPLIER_VISA_RATE_DATA_REQUEST_ERROR";




    //..Add Visa Offline...//
    export const ADD_VISA_OFFLINE_DATA_REQUEST =
    "ADD_VISA_OFFLINE_DATA_REQUEST";
    export const ADD_VISA_OFFLINE_DATA_REQUEST_FAIL =
    "ADD_VISA_OFFLINE_DATA_REQUEST_FAIL";
    export const ADD_VISA_OFFLINE_DATA_REQUEST_SUCCESS =
    "ADD_VISA_OFFLINE_DATA_REQUEST_SUCCESS";
    export const ADD_VISA_OFFLINE_DATA_REQUEST_ERROR =
    "ADD_VISA_OFFLINE_DATA_REQUEST_ERROR";


      //..Get All Visa Offline ...//
  export const GET_VISA_OFFLINE_DATA_REQUEST =
  "GET_VISA_OFFLINE_DATA_REQUEST";
  export const GET_VISA_OFFLINE_DATA_REQUEST_FAIL =
  "GET_VISA_OFFLINE_DATA_REQUEST_FAIL";
  export const GET_VISA_OFFLINE_DATA_REQUEST_SUCCESS =
  "GET_VISA_OFFLINE_DATA_REQUEST_SUCCESS";
  export const GET_VISA_OFFLINE_DATA_REQUEST_ERROR =
  "GET_VISA_OFFLINE_DATA_REQUEST_ERROR";


    //..Get Single Visa Offline For Edit ...//
    export const GET_VISA_OFFLINE_SINGLE_REQUEST =
    "GET_VISA_OFFLINE_SINGLE_REQUEST";
    export const GET_VISA_OFFLINE_SINGLE_REQUEST_FAIL =
    "GET_VISA_OFFLINE_SINGLE_REQUEST_FAIL";
    export const GET_VISA_OFFLINE_SINGLE_REQUEST_SUCCESS =
    "GET_VISA_OFFLINE_SINGLE_REQUEST_SUCCESS";
    export const GET_VISA_OFFLINE_SINGLE_REQUEST_ERROR =
    "GET_VISA_OFFLINE_SINGLE_REQUEST_ERROR";


        //.. Single Visa Offline Images Uploader ...//
        export const OFFLINE_VISA_IMAGE_REQUEST =
        "OFFLINE_VISA_IMAGE_REQUEST";
        export const OFFLINE_VISA_IMAGE_REQUEST_FAIL =
        "OFFLINE_VISA_IMAGE_REQUEST_FAIL";
        export const OFFLINE_VISA_IMAGE_REQUEST_SUCCESS =
        "OFFLINE_VISA_IMAGE_REQUEST_SUCCESS";
        export const OFFLINE_VISA_IMAGE_REQUEST_ERROR =
        "OFFLINE_VISA_IMAGE_REQUEST_ERROR";



         //..Get Rates For Offline Visa Posted ...//
         export const GET_RATES_POSTED_REQUEST =
         "GET_RATES_POSTED_REQUEST";
         export const GET_RATES_POSTED_REQUEST_FAIL =
         "GET_RATES_POSTED_REQUEST_FAIL";
         export const GET_RATES_POSTED_REQUEST_SUCCESS =
         "GET_RATES_POSTED_REQUEST_SUCCESS";
         export const GET_RATES_POSTED_REQUEST_ERROR =
         "GET_RATES_POSTED_REQUEST_ERROR";